sympa-community/sympa

- src/lib/Sympa/List.pm
Bug description: For some lists we have noticed a synchronization issue with the admin_table: an owner gets added to the list config file (through list family instanciation) but never appears in the admin_table. As a consequence this new list owner is not listed in the list panel on the web interface and does not have the expected privileges.
After a bit of code analysis and debugging I found out that revision 9948 is the cause of the problem: https://sourcesup.renater.fr/scm/viewvc.php/branches/sympa-6.1-branch/src/lib/List.pm?root=sympa&r1=9947&r2=9948
It turns out that List::sync_include_admin() subroutine mights never been run for a list if that list includes members from an external datasource but owner/editors get defined "statically" in the config list. To be more precise:
* …
> [bug][#11020] List admins changes not synchronized with admin_table

- default/mail_tt2/helpfile.tt2
- default/mail_tt2/listmaster_notification.tt2
- default/mail_tt2/listowner_notification.tt2
- default/mail_tt2/remind.tt2
- default/mail_tt2/sendpasswd.tt2
- default/mail_tt2/user_notification.tt2
- default/web_tt2/skinsedit.tt2
- default/web_tt2/subindex.tt2
These are some minor fixes riseup currently has to templates. They are mostly typo and grammar fixes, and s couple content adjustments.
> riseup fixes to templates

- default/web_tt2/error.tt2
- default/web_tt2/notice.tt2
- src/cgi/wwsympa.fcgi.in
- src/lib/Makefile.am
- src/lib/Sympa/List.pm
- src/lib/Sympa/List/Config.pm
- src/lib/Sympa/ListDef.pm
- src/lib/Sympa/Robot.pm
Rewriting code for list config semantics.
* New class Sympa::List::Config which may replace aged code.
* wwsympa/edit_list was rewritten along with following bug fixes:
* Possible crash due to malformed input.
* Can't remove the value of optional scalar parameter (e.g. custom_subject).
* LIST-editor address of the list itself can be set as value of editor.email.
* and several other insignificant bugs.
* Now configuration definition allows recursion with any depth.
* Processing of family constraint became simpler.
Config file parser would be also rewritten using this new class.
> [6.2] New code for list config semantics

- default/web_tt2/copy_template.tt2
- default/web_tt2/create_list_request.tt2
- default/web_tt2/css.tt2
- default/web_tt2/edit_list_request.tt2
- default/web_tt2/edit_template.tt2
- default/web_tt2/editsubscriber.tt2
- default/web_tt2/error.tt2
- default/web_tt2/get_biggest_lists.tt2
- default/web_tt2/get_inactive_lists.tt2
- default/web_tt2/get_latest_lists.tt2
- default/web_tt2/get_pending_lists.tt2
- default/web_tt2/lists.tt2
- default/web_tt2/ls_templates.tt2
- default/web_tt2/pref.tt2
- default/web_tt2/review_family.tt2
- default/web_tt2/set_pending_list_request.tt2
- default/web_tt2/setlang.tt2
- default/web_tt2/suboptions.tt2
- default/web_tt2/view_template.tt2
- src/cgi/wwsympa.fcgi.in
- src/lib/Sympa/Admin.pm
- src/lib/Sympa/Family.pm
- src/lib/Sympa/List.pm
- src/lib/Sympa/List/Config.pm
- src/lib/Sympa/ListDef.pm
- src/lib/Sympa/ListOpt.pm
- src/lib/Sympa/Robot.pm
- src/lib/Sympa/Template.pm
- t/parse_templates.t
- www/js/sympa.js
Entirely refactored edit_list_request.tt2. Simpler and consistent logic to compile configuration
Fixed bugs:
* [SourceSup#9741] "percentage of list members in VERP mode" is order by left justified
* Access privilege ("read" etc.) of paragraph did not override that of sub-parameter:
* e.g. If "archive" gives "read" privilege and "archive.web_access" gives "write", latter is editable on edit_list form but change is ignored.
* [SourceSup#7914] Web interface let define the same email twice as list owner.
* [SourceSup#9972] Existing item in member_include list configuration paragraph cannot be removed.
* Text parameter values including "%xx" are broken: For example "%a5" is altered to "/", "%3a" to ":".
* and several minor flaws.
Changes:
* List parameter "cookie" will be masked, even if it is …
> [6.2] Rewriting code on list configuration form

- src/lib/Conf.pm
- src/lib/Sympa/ListDef.pm
- src/lib/Sympa/Regexps.pm
This PR is intended to be fix to Issue #22.
Parameters for LDAP attribute description such as "include_ldap_query" did not allow those including option(s) like "cn;lang-ja".  Fixed regular expression to check their format according to [RFC2251, 4.1.5](https://tools.ietf.org/html/rfc2251#section-4.1.5).
> Issue #22: Parameters for LDAP attribute description are too restrictive

- src/lib/Sympa/HTMLSanitizer.pm
It makes sense to use the same options as previous versions. Specially AllowHref to don't strip hrefs of links
> Activating options in XSS Parser

- src/cgi/sympa_soap_server.fcgi.in
- src/cgi/wwsympa.fcgi.in
- src/lib/Sympa/SOAP/Transport.pm
FCGI scripts (wwsympa.fcgi and sympa_soap_server.fcgi) will not always restart when they are updated.
- exit(0) occurred only when script file is _updated_: This assumption is not always true. It would be better to occur whenever timestamp is simply _changed_.
- The time of startup was used for origin of change. Timestamp of script would be used instead.
- Non-standard `SCRIPT_FILENAME` CGI environment variable was referred. Instead use `$PROGRAM_NAME` (`$0`).
Note:
- Separate FastCGI server like spawn-fcgi needs restart.  With systemd, `Restart` directive may be useful. With traditional sysVinit script, manual restart may be required.
> FCGI scripts will not always restart when they are updated

- src/lib/Sympa/Spindle/AuthorizeRequest.pm
- src/sbin/sympa.pl.in
"sympa.pl --change_user_email" was broken on 6.2.20.
Fixed by reimplement it using Sympa::Request framework.
> "sympa.pl --change_user_email" was broken

- src/lib/Sympa/List.pm
[Submitted by B. Marchal, univ. Lorraine] When using '%' symbol in SQL data sources, said % was ignored because it was interpolated in subsequent sprintf. Fixed by escaping % sign.
> "%" sign in SQL data source would be escaped

- src/lib/Sympa/Language.pm
This change is related to issue #80 (and probably #52, #54).
When language context is not known, fallback setting `en` is used. Currently, it does not use translation catalog and there seems no easy way to correct artless messages.  This PR may solve the problem by trying to use `en_US` translation catalog for `en-US` also in `en` context: Corrections (at least minor ones) can be done modifying the translation.
> When fallback language "en" is used, use "en_US" translation catalog

- default/web_tt2/confirm_action.tt2
- src/cgi/wwsympa.fcgi.in
- src/lib/Sympa/Request.pm
- src/lib/Sympa/Request/Handler/add.pm
- [bug] Confirming subscription on web UI, custom attributes are broken.
- [bug] Authorizing subscription by owner may crash WWSympa.
- [bug] When subscription is authorized by owner, custom attributes submitted by user are omitted.
> Bugs on subscribe request with custom attributes and/or authorization

- src/lib/Sympa/Scenario.pm
We have an LDAP search filter that requires some SSL connection options that are not accepted as valid options, such as ca_file, use_tls, and ssl_ciphers. 
This patch updates the list of valid LDAP configuration options in Scenario.pm to include
`       use_tls ssl_version ssl_ciphers ssl_cert ssl_key ca_verify ca_path ca_file
`
With this change, Sympa 6.2.22 accepts our search filter options and properly handles the LDAP search filter.
> Add use_tls, ssl, version etc to valid LDAP options in Scenario.pm

- default/web_tt2/css.tt2
Our local branding guidelines require a color set that results in fairly dark colors for the top menu items, with a contrasting lighter color for the current item.
We found that when color_5 is set to something other than the default, the current menu item is still rendered as light blue instead of color_5.
Drawing from the code using color_6 immediately above it, this patch to css.tt2 uses color_5 as the background color for the active menu item when it is *not* being hovered over. 
With this update, the colors are as expected and the GUI seems to work correctly when driving under 6.2.22. That is, the current menu item is color_5 (e.g. burnt orange), the rest are color_6 (dark brown), and hovering the mouse over another menu item properly changes the background to color_5 (burnt orange) …
> Fix CSS attributes for un-hovered navigation menu items using color_5

- src/cgi/wwsympa.fcgi.in
- src/lib/Sympa/List.pm
- src/lib/Sympa/Request/Handler/move_list.pm
- src/lib/Sympa/Request/Handler/stats.pm
- src/lib/Sympa/SOAP/Transport.pm
- src/lib/Sympa/Scenario.pm
- src/lib/Sympa/Spindle/ProcessArchive.pm
- src/lib/Sympa/Spindle/ProcessAutomatic.pm
- src/lib/Sympa/Spindle/ProcessBounce.pm
- src/lib/Sympa/Spindle/ProcessDigest.pm
- src/lib/Sympa/Spindle/ProcessIncoming.pm
- src/lib/Sympa/Spindle/ProcessOutgoing.pm
- src/lib/Sympa/Spindle/ToList.pm
- src/lib/Sympa/Spindle/ToOutgoing.pm
- src/lib/Sympa/Spindle/TransformIncoming.pm
- src/lib/Sympa/Spool.pm
- src/lib/Sympa/Upgrade.pm
- src/sbin/task_manager.pl.in
When subscribers are imported, frequent write accesses to *listdir*`/stats` file occur.  This issue was reported by a listmaster.  According to investigation, content of this file must not being cached on memory, but rather be shared among processes.
Changes:
- Changes on subscribers, owners and editors will be "published" by updating timestamps of `.last_change.member` and `.last_change.admin` files in list directory.
- The last time of inclusion of  subscribers, owners and editors will be published by updating timestamps of `.last_sync.member` and `.last_sync.admin` files in list directory.
- 5th to 7th entries in `stats` file (total, last_sync, last_sync_admin) are removed.
Fixed bugs:
- [bug] Issue #7: Editing owners or editors on web UI requires restart to take effect.
- [bug] …
> Suppress saving stats file, and solve problem about on-memory cache

- src/libexec/alias_manager.pl.in
- src/sbin/archived.pl.in
- src/sbin/bounced.pl.in
- src/sbin/bulk.pl.in
- src/sbin/sympa.pl.in
- src/sbin/sympa_automatic.pl.in
- src/sbin/sympa_msg.pl.in
- src/sbin/sympa_newaliases.pl.in
- src/sbin/sympa_wizard.pl.in
- src/sbin/task_manager.pl.in
At least with kramdown, a variant of Markdown, two hyphens (`--`) in the text is altered to an en dash: See <https://github.com/gettalong/kramdown/issues/472>.  To avoid it, use `C<...>` instead of `B<...>` etc. in POD.
> Changes on POD format for transition to Markdown

- src/cgi/wwsympa.fcgi.in
- src/lib/Sympa/List.pm
- src/lib/Sympa/Request/Handler/open_list.pm
- When list is closed, list could be marked error_config. Fixed by checking owner only when list is open or peinding.
- When list is restored, long time could be taken before owners/editors are restored.
> Insignificant bugs related to cache

- src/lib/Sympa/List.pm
- src/lib/Sympa/ListDef.pm
- src/lib/Sympa/ListOpt.pm
- src/lib/Sympa/Message.pm
Remove "html" reception mode and make it a synonym of "mail" (default) mode.
This may fix issue #125.
> Remove "html" reception mode #125

- .travis.yml
- src/lib/Sympa/Language.pm
- t/Language.t
This bug was reported by a japanese listmaster.  Users in non-Latin-1 languages (language other than "en", "de", "fr", ...) will notice this bug. Latin-1 users rarely realize it but warnings are spit out to error log:
```
wwsympa.fcgi: Use of wide characters in FCGI::Stream::PRINT is deprecated and will stop wprking in a future version of FCGI at /usr/local/lib/perl5/site_perl/mach/5.24/Template.pm line 162.
```
Background: Starting with Perl 5.22.0, POSIX::strftime() returns Unicode (utf8 flag set) string under UTF-8 locale.
- https://metacpan.org/pod/release/SHAY/perl-5.26.1/pod/perl5220delta.pod#Better-heuristics-on-older-platforms-for-determining-locale-UTF-8ness
- https://perl5.git.perl.org/perl.git/commit/9717af6d049902fc887c412facb2d15e785ef1a4
Sympa::Language::gettext_strftime() …
> Characters in pages are garbled (get "mojibake") with Perl 5.22.0 or later

- src/lib/Sympa/ConfDef.pm
- src/lib/Sympa/ListDef.pm
`default_ttl` configuration parameter was restored. It was removed on 6.2 pre-alpha without specific reason.
This may fix issue #145.
> Restore default_ttl #145

- default/create_list_templates/confidential/config.tt2
- default/create_list_templates/hotline/config.tt2
- default/create_list_templates/html-news-letter/config.tt2
- default/create_list_templates/intranet_list/config.tt2
- default/create_list_templates/news-letter/config.tt2
- default/create_list_templates/private_working_group/config.tt2
- default/create_list_templates/public_web_forum/config.tt2
- src/cgi/wwsympa.fcgi.in
- src/lib/Sympa/Family.pm
- src/lib/Sympa/Request/Handler/create_list.pm
- src/sbin/sympa.pl.in
- [bug] Feature of create_list is *not* the same as what described in documentation:
- description (info) parameter is not mandatory.
- the "moderator" parameter in documentation has never been implemented: "editor" would be used.
- moreover, "moderator" was treated either as [multiple values](http://www.sympa.org/manual/list-families#configtt2) or [single value](http://www.sympa.org/manual/list-creation#xml_file_format) in a few parts of documentation.
- "topic" was implemented as documentation describes, not "topics", but some of code uses "topics".
Fixed, with implementing "moderator" attribute in XML file as synonym of "editor", allowing both single and multipe values.
**NOTE**: Inconsistencies in documentation were fixed on [the new documentation …
> Inconsistencies in implementation and documentation of typical list profile (create list templates)

- src/sbin/sympa.pl.in
Fixes several typos on print/printf including case of issue #159.
> Issue #159

- src/cgi/wwsympa.fcgi.in
- [bug] After successful login, user may see the empty page instead of being redirected to home page. This can occur with at least [Apache mod_proxy_fcgi](https://httpd.apache.org/docs/2.4/mod/mod_proxy_fcgi.html).
Because, server-side FastCGI support may require explicit "Status: 302" response header field for redirection, not only "Location:" field; if backend had not given "Status:" field, default "200" can be assumed (cf. RFC 3875 6.3.3).
Fixed by adding "Status: 302 Moved" field to redirecting response.
> WWSympa: Redirect without Status field may bring to empty page

- src/etc/script/Makefile.am
- src/etc/script/nginx-sympasoap.servicein
- src/etc/script/nginx-wwsympa.servicein
`libexecdir` is misleadingly used instead of `execcgidir` in src/etc/script/Makefile.am
> "libexecdir" is misleadingly used instead of "execcgidir"

- default/web_tt2/picture_upload.tt2
- src/cgi/wwsympa.fcgi.in
This fixes #180, but I'm not completely satisfied with the fix, as the pictures_max_size will be properly reported but the size will be expressed in bytes, while it would probably be better to report it in kilobytes.
> Pictures max size fix

- www/Makefile.am
This creates $staticdir/pictures as noticed in #172 in a smilar way the css directory creation was fixed with https://github.com/sympa-community/sympa/commit/85a6217e2657bfffdb884179d0feaed78c8b53e6
> Create $staticdir/pictures directory

- Makefile.am
This may fix issue #195.
Sources checked out from repository lacks *.mo test data files so that some tests in t/Language.t fail. Only "make dist" generate these files.
Fixed by letting check-local rule depend on test files.
> #195: Some tests fail with checked out source

- www/external/foundation/js/foundation/foundation.tooltip.js
May fix issue #206
This looks a bug of Foundation 5 not yet fixed. Applied a fix suggested by Brian Lenz at zurb/foundation-sites#6944
> Issue #206: Firefox freezes on "Edit robot config" page

- src/cgi/wwsympa.fcgi.in
- src/lib/Sympa/List.pm
If a user cannot access to list info page, error message will no longer be shown. Instead, the user quietly redirected to home page. This change deals with two cases:
- If a user successfully subscribed to a list and it's private list, user would see rejection message, because they have not logged in.
- User could know whether arbitrary list exists or not, because private list rejected them with the message different from non-existing list.
This may fix issue #193.
Known bug: On web interface, `info.conceal` and `info.private` scenarios behave the same (even without change above).
> WWSympa: Change behavior about info function and unknown list

- src/lib/Sympa/Database.pm
- src/lib/Sympa/DatabaseDescription.pm
- src/lib/Sympa/DatabaseDriver.pm
- src/lib/Sympa/DatabaseDriver/MySQL.pm
- src/lib/Sympa/DatabaseDriver/ODBC.pm
- src/lib/Sympa/DatabaseDriver/Oracle.pm
- src/lib/Sympa/DatabaseDriver/PostgreSQL.pm
- src/lib/Sympa/DatabaseDriver/SQLite.pm
- src/lib/Sympa/DatabaseDriver/Sybase.pm
- src/lib/Sympa/List.pm
- src/lib/Sympa/Upgrade.pm
This PR deprecates datetime field type in database.  Because:
- There are no portable way to compare, increase or decrease such field values.
- It's slow: Values should be converted to Unix timestamp; Index cannot be applied.
Database will be upgraded automatically during upgrading process.
> Deprecate datetime field type in database

- src/bin/upgrade_sympa_password.pl.in
- src/lib/Sympa/Auth.pm
- src/lib/Sympa/ConfDef.pm
- src/lib/Sympa/DatabaseDescription.pm
- src/lib/Sympa/ModDef.pm
- src/lib/Sympa/User.pm
Some Sympa sites may find it desirable to use other password hash functions than MD5. At our site we have been looking at Bcrypt, which has useful properties like supporting a random salt and scaling in expense as computing power becomes cheaper over time. Both features make it much more costly to crack a site's user passwords if they are revealed in some way. 
Since Sympa has already modularized password hashing in `Sympa::User::password_fingerprint`, we found that the changes required for basic Bcrypt support are relatively small in number:
- add new sympa.conf options to select and control Bcrypt hashes:
- `password_hash`: `md5` or `bcrypt` (default `md5`)
- `bcrypt_cost`: integer value used to determine the "cost" parameter of the Bcrypt algorithm (default `12`)
- update …
> Feature: support for Bcrypt password hashes

- src/cgi/wwsympa.fcgi.in
- src/lib/Conf.pm
- src/lib/Sympa/ConfDef.pm
- src/lib/Sympa/List.pm
- src/lib/Sympa/Tools/WWW.pm
- src/lib/Sympa/Upgrade.pm
This PR may fix bug of change on issue #172.
- [bug] Values of css_url & css_path parameters by robot are broken.
- [change] css_url & css_path no longer may be per-robot parameters.  Because robot subdirectories under CSSDIR are assumed.
- [change] pictures_url & pictures_path may not be per-robot parameters, as proposed in original PR.  Because list subdirectories under PICTURESDIR are assumed.
**This would be merged in a day for quick fix.**
> Fix bug by change of issue #172

- src/cgi/wwsympa.fcgi.in
After building and installing a copy of 6.2.25b.3, the 'my lists' page showed the expected lists. However, clicking the 'info' or 'admin' links resulted in a return to the home page and a wwsympa.log entry of the form
``Mar 19 21:01:52 HOSTNAME wwsympa[21958]: info main:: [robot ROBOT] [session 65344701597375] [client IPADDR] [user ADDRESS] Unknown list "LISTNAME"
``
Based on some debug logging and poking around, it looks like a call to `List->new()` in wwsympa.fcgi has the robot and list parameters reversed: 
``unless ($list = Sympa::List->new($robot, $in{'list'})) {``
Updating this to
``unless ($list = Sympa::List->new($in{'list'}, $robot)) {``
restores the expected behavior.
> wwsympa.fcgi.in: fix calling order for List->new(): should be (list, robot)

- src/lib/Sympa/Upgrade.pm
[bug] As the field `date_admin` and `date_subscriber` are no longer used but they have `NOT NULL` constraint, they should be deleted.
This may fix issue #240.
This bug affects PostgreSQL and Oracle; MySQL (without strict mode) and SQLite may not be affected.
> Issue #240: Unable to edit owners/subscribers

- src/bin/upgrade_sympa_password.pl.in
- src/lib/Sympa/User.pm
This PR contains updates for the bcrypt hash support, based on tag 6.2.25b.3.
-- Fix some undef string interpolation errors in `User.pm` when running in Perl strict mode
--  `password_fingerprint()` now uses `password_hash_update` as a flag to control whether old hash types are honored when a new hash algorithm is chosen.
** `1` = honor old hashes *and* update the user_table upon user login, for a graceful transition
** `0` = only use the system configured hash type; users with old hashes must set a new password
This behavior better fits expectations and the recently created documentation. 
Just to note in case it should be changed, the default for `password_hash_update` is currently `1`.
-- Calculating updated hashes for tens of thousands of users with an intentionally expensive …
> Updates for bcrypt support

- src/lib/Sympa/DatabaseDriver/LDAP.pm
- src/lib/Sympa/List.pm
- src/lib/Sympa/ModDef.pm
This may fix issue #234.
Fixed by:
- Canonicalizing value of attrs1 as DN, if it is search base or root of it.
- Escaping it as attributevalue in DN otherwise.
> Issue #234: Sympa ldap search escapes chars incorrect

- src/lib/Sympa/Spindle/TransformOutgoing.pm
Improvement: Setting value "field:value" will remove fields with specified value.
Background: Setting value such as "precedence:list" fixes issue #110.
> Improve remove_outgoing_headers list parameter

- default/web_tt2/d_read.tt2
- default/web_tt2/help_shared.tt2
- default/web_tt2/review.tt2
- default/web_tt2/reviewbouncing.tt2
- default/web_tt2/viewlogs.tt2
- src/lib/Sympa/WWW/SharedDocument.pm
- www/Makefile.am
Several images under `STATICDIR/icons` will not be used as described in below.
Following images will be used continuously:
- `favicon_sympa.png` (favicon)
- `logo_sympa.png` (logo)
- `crosshairs.png` (used by color picker)
- `h.png` ( ,, )
- `position.png` ( ,, )
- `sv.png` ( ,, )
Following images will no longer be used:
- `binary.png` (used by shared document repository)
- `folder.png` ( ,, )
- `image2.png` ( ,, )
- `link.png` ( ,, )
- `movie.png` ( ,, )
- `sound1.png` ( ,, )
- `text.png` ( ,, )
- `unknown.png` ( ,, )
- `left.png`
- `right.png`
Following images have no longer been used by current stable:
- `arc.png`
- `back.png`
- `begin.png`
- `config.png`
- `datasources.png`
- `down.png`
- `end.png`
- `folder.open.png`
- `junk.png`
- `locked.png`
- `logo-s-lock.png` (older logo, small, …
> Use font-awesome icons instead of stock images

- default/web_tt2/d_properties.tt2
- default/web_tt2/editfile.tt2
- default/web_tt2/modform.tt2
- default/web_tt2/modindex.tt2
- default/web_tt2/serveradmin.tt2
- default/web_tt2/set_pending_list_request.tt2
- default/web_tt2/suboptions.tt2
- default/web_tt2/subscribe.tt2
- default/web_tt2/suspend_request.tt2
- default/web_tt2/ticket.tt2
There was a period both in the localization string and outside it in these sentences. This error caused doble periods to be displayed in the rendered pages.
> Removed extra periods at the end of these sentences

- default/web_tt2/review.tt2
- default/web_tt2/reviewbouncing.tt2
- src/cgi/wwsympa.fcgi.in
- src/lib/Sympa/List.pm
- src/lib/Sympa/Request/Handler/close_list.pm
- src/lib/Sympa/Request/Handler/move_list.pm
- src/lib/Sympa/Request/Handler/open_list.pm
- src/lib/Sympa/Upgrade.pm
- src/sbin/sympa.pl.in
Changes:
- If list is closed, members, owners and editors are dumped to files `member.dump`, `owner.dump` and `editor.dump` in `EXPLDIR/`_list path_`/` directory.  On previous versions, only members were dumped and file name was `subscriber.closed.dump`.
Improvements:
- New and improved options for `sympa.pl`:
- ~~`--dump`~~ `--dump_users` dumps list members/owners/editors to file under list directory.
- ~~`--suck`~~ `--restore_users` restores list members/owners/editor from this file.  This is the new option.
- Note that dump files are the same as those created when list is closed.  ~~`--dump`~~`--dump_users` and ~~`--suck`~~`--restore_users` work only on open list and closed/pending lists are omitted.    On previous versions of Sympa, only members were dumped and file name was …
> sympa.pl: Improving --dump_users and adding --restore_users, and related fixes

- default/web_tt2/edit.tt2
- default/web_tt2/info.tt2
- default/web_tt2/list_panel.tt2
- default/web_tt2/nav.tt2
- default/web_tt2/review.tt2
- default/web_tt2/reviewbouncing.tt2
- default/web_tt2/set_pending_list_request.tt2
- src/cgi/wwsympa.fcgi.in
- src/lib/Sympa/List.pm
- src/lib/Sympa/ListDef.pm
- src/lib/Sympa/Request/Handler/close_list.pm
- src/lib/Sympa/Request/Handler/create_automatic_list.pm
- src/lib/Sympa/Request/Handler/create_list.pm
- src/lib/Sympa/Request/Handler/move_list.pm
- src/lib/Sympa/Request/Handler/open_list.pm
- src/lib/Sympa/Upgrade.pm
- src/sbin/sympa.pl.in
- www/js/sympa.js
This PR depends on PR #267.
----
Bug fix:
- Issue #11: Spurious error on duplicate keys with admin sync
- Now sync_include_admin() passes cache and updates admin_table directly.
- It no longer reload owner/editor in list config.
Changes/improvements:
- Form to edit owners and moderators are removed from list config page: They have their own menus.
- When a list is created, initial owners and moderators are importd from dump file in list directory: `owner` and `editor` parameters in `config` file are no longer loaded.
- However, when list is created using list creation template, `owner` and `editor` are split into dump files automatically: users need not update `config.tt2`.
- And however, when administrator manually creates a list by creating list directory and `config` file, they also …
> #11: Spurious error on duplicate keys with admin sync, and changes on configuration for owners/moderators

- src/lib/Conf.pm
- src/lib/Sympa/Upgrade.pm
As sympa.conf/robot.conf won't be reloaded by current version, binary cache for these files are useless. Fixed by not checking updates on these files.  Worse, even if a new parameter was added, cached configuration will be used and new parameter will be undefined instead of default value.
For example see issue #280.
This PR removes feature of binary cache for sympa.conf/robot.conf.
> Binary cache files for sympa.conf/rebot.conf are useless

- default/web_tt2/aside_menu.tt2
- default/web_tt2/compose_mail.tt2
- default/web_tt2/crash.tt2
- default/web_tt2/create_list_request.tt2
- default/web_tt2/css.tt2
- default/web_tt2/d_read.tt2
- default/web_tt2/header.tt2
- default/web_tt2/list_menu.tt2
- default/web_tt2/loginbanner.tt2
- default/web_tt2/main.tt2
- default/web_tt2/nav.tt2
- default/web_tt2/review.tt2
- default/web_tt2/tt2_error.tt2
- www/js/sympa.js
See #170.
Fixes/Changes/Improvements:
- Improve "Please wait..." text to place it at center of display.
- Prevent spacing between items of top bar because of inline-block rendering (See PR #187 bug 1).
- Icons in home page are warped (See 3).
- Consistent headings and title bars.
Known bug:
- In environments without CSS/javascript support, redundant texts with heading (h2) and title bar are shown.
> Foundation6: Additional fixup

- src/lib/Makefile.am
- src/lib/Sympa/Family.pm
- src/lib/Sympa/List.pm
- src/lib/Sympa/Request/Handler/update_automatic_list.pm
This may fix #309.
* New request handler `update_automatic_list`.
* A few insignificat bug fixes.
Known bug:
* If update failed (aborted), list files (config etc.) will be kept updated: Roll back won't occur.
> Family updates don't propagate owners/editors changes in the database #309

- Makefile.am
- po/sympa/Makefile.in.in
- po/sympa/xgettext.pl
- src/lib/Makefile.am
- src/sbin/sympa_wizard.pl.in
Let `sympa_wizard.pl --check` use `cpanfile`. Deprecating `Sympa::ModDef`.
Known bug:
- As `cpanfile` does not contain requirements about Perl,  warning is spewed.
> Deprecate ModDef.pm

- src/lib/Sympa/DatabaseDriver/PostgreSQL.pm
See #305.
PostgreSQL: Strings got from database can have utf8 flag, and cause mojibake (breakage of texts) or crash by double-decoding.  Past fix on [r12821](https://github.com/sympa-community/historic-sympa/commit/88ac051) was insufficient because it dealt with input strings only.
~~Known bug: Past fix may crash with DBD::Pg 3.6.x or later.~~ maybe fixed.
> Candidate fix for #305, #308

- default/scenari/send.confidential
> [-bug] Title of send.confidential and send.private are the same.

- default/web_tt2/modindex.tt2
Added the missing button for reporting spam i bulk. This fix ignores the ham/spam status off the messages. All will be delivered to the script. 
Tried to tidy the page up a bit by moving the bulk control buttons to the bottom off the "messages for moderation" table. The table itself should probably be changed to match the other tables in sympa (see the subscriber table)
> Support for spam reporting in bulk. Moved the bulk moderation controls.

- www/js/foundation/css/foundation-float.css
Fix about #170.
This occurs at leaset with recent versions of Chrome and Firefox enabling developer tools.
> Reference to map file causes HTTP 404 errors

- src/lib/Sympa/WWW/SOAP.pm
> SympaSOAP: closeList crashes.

- cpanfile
As discussed on the [ML](https://listes.renater.fr/sympa/arc/sympa-developpers/2018-05/msg00065.html), we should drop MHonArc::UTF8 version in cpanfile since it prevents to install dependencies with `cpanm --installdeps`.
> [cpanfile] Drop MHonArc::UTF8 version

- src/lib/Sympa/Message.pm
Sympa currently uses rsa-sha1 for DKIM signature attached to outgoing mails. It [has been shown](https://shattered.io/) that SHA-1 can no longer be considered resistant to collisions in practice, which means that it is inadequate to be used with DKIM. Since Mail::DKIM supports rsa-sha256, this is easy to fix.
> Use rsa-sha256 for DKIM signatures

- src/lib/Sympa/List.pm
When instantiating a family, unknown lists are never closed because the SQL query to retrieve the existing instantiated lists of the family is incorrect.
This PR fixes the SQL query and makes the "--close_unknown" argument work again.
> Fix SQL query to fetch all lists of a family

- src/lib/Sympa/Request/Handler/close_list.pm
- src/lib/Sympa/Task.pm
When purging a closed list, all tasks are instantiated which can be a very long process when you have thousands of lists defined.
This PR improves the purge operation by only instantiating tasks relevant to the list being purged.
> Improve performance of purge operation

- default/mhonarc-ressources.tt2
- Autocrypt: Autocrypt level 1 header field https://autocrypt.org/
- Openpgp: The "OpenPGP" mail and news header field https://tools.ietf.org/html/draft-josefsson-openpgp-mailnews-header-07
Note: Rebuilding archives is required to apply this modification to past archives.
This may fix issue #316.
> #316: Don't show "Autocrypt:" and "Openpgp:" header fields in web archives.

- default/web_tt2/css.tt2
- default/web_tt2/help.tt2
- default/web_tt2/info.tt2
Due to customization by UX components (Foundation etc.), styles of help contents are broken.
This PR fixes CSS to reset customization so that help contents (and list homepage) will be rendered properly.
| Broken style | Fixed style |
| ------------ | ----------- |
| <img title="Broken style" src="https://user-images.githubusercontent.com/5743546/42732885-4bc0b67a-8864-11e8-886b-4871750294dc.png" /> | <img title="Fixed style" src="https://user-images.githubusercontent.com/5743546/42732912-c058081c-8864-11e8-9fb2-1b64d97a1a80.png" /> |
> Styles for help contents are broken.

- default/web_tt2/css.tt2
With IE at least 11 or earlier.  Menu items may be off to bottom.
| Broken | Fixed by this PR |
| ------ | ---------------- |
| ![ie](https://user-images.githubusercontent.com/5743546/42742761-ab575b2c-88f8-11e8-911c-0e31cc25cb24.png) | ![ie_fixed](https://user-images.githubusercontent.com/5743546/42742782-d31efc6e-88f8-11e8-8914-7ba68d7bf655.png) |
> WWSympa: Rendering bug with IE

- src/etc/script/sympa.in
https://github.com/sympa-community/sympa/issues/376
Currently sysv script always return 0 even if service is stopped which breaks
many checks which rely on LSB standards.
Signed-off-by: Konstantin A. Lepikhov <lakostis@altlinux.ru>
> sympa.in: make sysv script LSB friendly

- src/cgi/wwsympa.fcgi.in
When searching for an _existing_ list using the 'Search Form', any leading or trailing whitespace is included in the submitted search value. This causes the search to fail to find any list by the submitted value.
This PR fixes the 'Search Form' by removing any trailing/leading whitespace from the value submitted.
> Fix do_search_list sub to trim leading/trailig whitespace

- src/lib/Sympa/List.pm
At our site we encountered some cases where the same source ID was present multiple times in the `include_sources_subscriber` column of the `subscriber_table`. The current code simply adds new source ID's to the end of the current list, without any checks.  This update adds a small utility function that suppresses duplicate source ID's when adding them to the list.
> List.pm: ensure uniqueness when adding to source id list

- src/lib/Sympa/List/Users.pm
Updates for the `owner_domain` global validation code:
* The change in context for validating owner updates effectively disabled the `owner_domain` global validation in 6.2.34. The update obtains the current list configuration separately via `$self->{context}`, rather than expecting `$self` to be a complete list configuration hash. This allows the validation function to obtain the current `owner_domain` and `owner_domain_min` config parameters for the list.
* When `owner_domain` is in effect, updating owner's personal name and other fields failed unless the owner mail address also changed. The update is more careful to only look at owner address changes.
* Tweak the logging to hopefully be a little more informative when enabled
> 6.2.34 owner_domain fixes 

- default/mail_tt2/user_notification.tt2
- default/scenari/subscribe.auth
- default/scenari/subscribe.auth_notify
- default/scenari/subscribe.auth_notifydkim
- default/scenari/subscribe.auth_owner
- default/scenari/subscribe.auth_ownerdkim
- default/scenari/subscribe.authdkim
- default/scenari/subscribe.closed
- default/scenari/subscribe.intranet
- default/scenari/subscribe.intranetorowner
- default/scenari/subscribe.open
- default/scenari/subscribe.open_notify
- default/scenari/subscribe.open_quiet
- default/scenari/subscribe.owner
- default/scenari/subscribe.smime
- default/scenari/subscribe.smimeorowner
- default/scenari/unsubscribe.auth
- default/scenari/unsubscribe.auth_notify
- default/scenari/unsubscribe.auth_notifydkim
- default/scenari/unsubscribe.authdkim
- default/scenari/unsubscribe.closed
- default/scenari/unsubscribe.open
- default/scenari/unsubscribe.open_notify
- default/scenari/unsubscribe.owner
- src/cgi/wwsympa.fcgi.in
- src/lib/Sympa/Spindle/AuthorizeRequest.pm
- [feature] When an other user (or anonymous user on web interface) requested subscribing/unsubscribing, if target user already subscribed / not yet subscribed to the list, they will be informed someone requested action while no actions will be taken.  Also, fake response will be sent to requester to prevent sniffing users.
- [change] Update subscribe.* and unsubscribe.* scenarios: Now authentication by target user is required when anonymous/other user requested these actions.  Previously, if "open" scenario was used, an anonymous user on web interface could add subscriber without confirmation.
This may fix issue #386.
This is not applicable to Sympa 6.2.24 and earlier (due to changes of module names).
> Notify user that he already subscribed to a list #386

- src/lib/Sympa/User.pm
In 6.2.32 and 6.2.34, our testing shows that using the GUI to add an existing address to a list causes the user's current password hash to be rehashed and stored. This renders the user's password unusable and effectively forces a password reset sequence. The behavior seems to correspond with the spontaneous password reinitialization problem discussed in #269. 
This targeted fix uses `hash_type()` to detect password hashes and avoid rehashing them. For the sake of consistent behavior, both `update_global_user()` and `add_global_user()` are updated.
The change does not address all of the design concerns of #269 but in our testing it does prevent the seemingly spontaneous password resets caused by being added to a list using the GUI.
> Avoid rehashing user password hashes in {add,update}_global_user()

- configure.ac
This directory was originally prepared for [upstart](http://upstart.ubuntu.com/) which has been adopted by Fedora/RHEL, Debian/Ubuntu etc. (On Systemd, this directory is included in `tmpfiles.d/legacy.conf` for compatibility with "legacy" systems).
Thus, I believe the default value of this option should not depend on `--prefix` option of each application.
See also issue #274.
> Let the default of `--with-lockdir` be `/var/lock/subsys` always

- src/cgi/wwsympa.fcgi.in
As of Sympa 6.2.34, `wwsympa_url` parameter became optional.  This PR will make WWSympa responding with status 404 (Not Found) when this parameter is unavailable for particular domain (specified neither in `robot.conf` nor `sympa.conf`).
> Domain without available wwsympa_url parameter should deny web access

- src/etc/script/Makefile.am
- src/etc/script/sympa.servicein
- src/etc/script/sympasoap.servicein
- src/etc/script/wwsympa.servicein
- [bug] Systemd: PIDDIR may not exist at startup. Fixed by creating it with `sympa.service`.
- [-change] Rename `nginx-wwsympa.service` and `nginx-sympasoap.service` files to `wwsympa.service` and `sympasoap.service`: They may be used by other httpd.
> Update startup scripts

- src/cgi/wwsympa.fcgi.in
This may fix issue #268.
- "referer" and "failure_referer" parameters in login form are allowed only if it is http/https URL and within scope of cookie_domain.
> Issue #268: XSS and open redirect on WWSympa

- default/web_tt2/main.tt2
- src/cgi/wwsympa.fcgi.in
- src/lib/Sympa/ConfDef.pm
- src/lib/Sympa/Upgrade.pm
> Drop support for htmlArea.

- cpanfile
- po/sympa/es.po
- po/sympa/fr.po
- po/sympa/gl.po
- src/bin/Makefile.am
- src/lib/Conf.pm
- src/lib/Makefile.am
- src/lib/Sympa/ConfDef.pm
- src/sbin/sympa_wizard.pl.in
I hear there are no users using Sybase (Adaptive Server Enterprise).  This PR will drop support for it.
This may close issue #147.
> Formally drop support for Sybase

- default/web_tt2/head_javascript.tt2
- default/web_tt2/stats.tt2
- src/lib/Sympa/Template.pm
This may fix #428 and potential other bugs.
- Introduce a new tt2 filter escape_cstr for C-style escaping.
- Escape template variable passed to javascript.
> Template strings passed to javascript were not escaped

- src/lib/Sympa/List.pm
Sometimes (while manually creating a robot) in testing or production mode, it could be useful to have this feature implemented.
1. It makes possible to load the robot configuration (from the wwsympa side) without issues even if ${expldir}/${robot} does not exists
2. It makes possible to create a first list even if ${expldir}/${robot} does not exists
Feel free to reject it if you think it is not suitable.
Maybe this PR could help people to save time.
> Create ${expldir}/${robot} directory if it does not exists

- src/lib/Sympa/WWW/Tools.pm
Timestamp of css.tt2 is not always increased by each new installation: It can be decreased.
Fixed by copying timestamp of original css.tt2 to generated CSS.
> CSS cannot be updated if css.tt2 was older than previously generated CSS.

- doc/list_config.podpl
- src/lib/Sympa/ListOpt.pm
- src/lib/Sympa/Template.pm
- [-bug] An external module Class-Singleton required during `make`.
Fixed by making Sympa::ListOpt not depending on Sympa::Language.
This may fix issue #434.
> External module required during `make` #434

- doc/Makefile.am
- [-bug] doc/Makefile: Intermediate files list_config.pod etc. won't be cleared and failed to update target files.
This may fix issue #435.
> doc/Makefile: Fails to build list_config.5 etc. #435

- src/bin/sympa_test_ldap.pl.in
- src/lib/Conf.pm
- src/lib/Sympa/ListDef.pm
- src/lib/Sympa/ListOpt.pm
- src/libexec/ldap_alias_manager.pl.in
This PR may add support for TLSv1.3 (RFC8446) for LDAP-related functions of Sympa.
Change:
- Corresponding parameters and command line arguments allow an additional option `tlsv1_3`.
Note:
- Actual support needs following components:
- OpenSSL library 1.1.1 or later
- IO-Socket-SSL 2.060 or later
> Add support for TLSv1.3

- src/lib/Sympa/DatabaseManager.pm
At 6.2a.29 r7637, family_exclusion field became a part of primary key.  But it could contain NULL and may break not_null constraint during upgrade from earlier version.
Fixed by replacing NULL with '' before primary key will be added.
This PR may fix issue #442.
> family_exclusion field can break not_null constraint during upgrade #442

- src/cgi/wwsympa.fcgi.in
- src/lib/Sympa/Aliases.pm
- src/lib/Sympa/List.pm
- src/lib/Sympa/Request/Handler/create_automatic_list.pm
- src/lib/Sympa/Request/Handler/create_list.pm
- src/lib/Sympa/Request/Handler/move_list.pm
- [bug] The lists with bounce addresses for VERP/tracking can be created.
By this PR, creation of lists with following addresses may be denied:
- `bounce` `@`_`domain`_
- `bounce` `+`_`emptyorarbitrarystring`_`@`_`domain`_
- Small refactoring.
This PR depends on PR #454.
> The lists with "bounce" addresses should not be created

- src/lib/Sympa/Upgrade.pm
> Candidate fix for issue #459

- src/lib/Sympa/List.pm
`*_include` list parameter won't parse template if `souorce_parameters` was not defined.
Fix for issue #461.
> Template parsing problems in parameterizable data sources #461

- src/cgi/wwsympa.fcgi.in
- src/lib/Sympa/WWW/Tools.pm
If cookie_domain is not set, "Does NOT match HTTP_HOST" is logged everytime.
This PR may fix it by lowering log level.
> WWSympa: Suppress verbose log on cookie

- default/Makefile.am
- default/web_tt2/list_menu.tt2
- default/web_tt2/report_abuse.tt2
- src/cgi/wwsympa.fcgi.in
- src/lib/Sympa/ConfDef.pm
> Fix #323 — Add "Report abuse" button to lists side menu

- src/lib/Sympa/DatabaseDriver/LDAP.pm
- src/lib/Sympa/List.pm
> Datasource: On LDAP 2 level query, attr1 as DN should not be canonicalized

- src/etc/script/sympa.in
Issue https://github.com/sympa-community/sympa/issues/72 states that "we should stop supporting init scripts as modern distributions are using systemd". I have to disagree. Gentoo Linux defaults to OpenRC, so I created a small pull request to fix missing quotes in the init script.
> Fix missing quotes in init script

- src/lib/Sympa/List.pm
- src/lib/Sympa/Tools/Data.pm
- src/lib/Sympa/Tools/Text.pm
`custom_attribute` field in `member.dump` control file is broken. Fixed by serializing content.
> Broken `custom_attribute` field in `member.dump`

- src/cgi/wwsympa.fcgi.in
On Debian 9, with perl 5.24.1 and Archive::Zip 1.59 and 1.64, uploading
a zip file to let Sympa (6.2.34) unzip it and put its files into shared
docs fails.
The zip member is a CGI::File::Temp instance and can seek but fails to
be extracted ("Unable to extract member XXX of the zip file" in Sympa
logs).
Unconditionnally blessing the file handle to IO::File fixes the failure.
> Fix shared docs zip upload to send multiple files at once

- src/lib/Sympa/List.pm
Additional fix for #476 which is related to #474.
Net::LDAP::Util module is optional.
> Additional fix for #474.

- .gitlab-ci.yml
For those who prefer to work on Gitlab (or [use Gitlab CI while using Github](https://about.gitlab.com/solutions/github/)), here's a working `.gitlab-ci.yml`.
Docker images for the CI are published on https://framagit.org/luc/DockerFiles/tree/master/sympa-perl
> Allow to use Gitlab CI

- src/lib/Sympa/WWW/Tools.pm
[bug] Older CSS files would be cleared.
Fixed by clearing older `style.css*` and `lang.css*` under $CSSDIR when they would be updated.
Note:
* Among files under $CSSDIR, `fullPage.css*`, `print.css*` and `print-preview.css*` will no longer be used nor updated. These may be removed manuallly.
> WWSympa: Older CSS files would be cleared

- src/lib/Sympa/Tools/Text.pm
Fixed by preventing folding words matching email regexp.
This may fix #502.
> Long email addresses in system messages may be folded #502

- default/web_tt2/viewlogs.tt2
- src/cgi/wwsympa.fcgi.in
- src/lib/Sympa/Upgrade.pm
- src/sbin/sympa_wizard.pl.in
* [bug] Extension of backup files created during upgrade process were localised by gettext_strftime() so that they may contain inappropriate characters such as spece.  Fixed by making extensions untranslated.
* Another unuseful use of gettext_strftime() in a template.
> File extension may contain spaces by using gettext_strftime()

- .gitignore
- Makefile.am
- doc/Makefile.am
- doc/list_config.podpl
- src/lib/Makefile.am
Running `make distcheck` aborts due to missing dependencies, because some rules in `Makefile.am` didn't take care of `$(srcdir)` and `$(builddir)`.
> `make distcheck` fails

- src/lib/Sympa/List.pm
- [-bug] A scalar parameter in list config without value and separator is warned.
See GH issue #468, Additional information.
> A scalar parameter in list config without value is warned

- src/sbin/sympa.pl.in
`sympa.pl --upgrade_config_location` doesn't respect configured user/group but always uses "`sympa`"/"`sympa`".
Fixed by using `USER`/`GROUP` in `Sympa::Constants`.
> `sympa.pl --upgrade_config_location` doesn't respect configured user/group

- src/etc/script/sympa-archive.servicein
- src/etc/script/sympa-bounce.servicein
- src/etc/script/sympa-outgoing.servicein
- src/etc/script/sympa-task.servicein
- src/etc/script/sympasoap.servicein
- src/etc/script/wwsympa.servicein
wwsympa and sympasoap do not strictly require the other sympa services to be
useful. However, BindsTo enforces that in both systemd unit files, thus replace
with After.
> Weaken sympa and wwsympa/sympa soap link

- default/Makefile.am
- default/web_tt2/config_common.tt2
- src/lib/Sympa.pm
- src/lib/Sympa/List.pm
- src/lib/Sympa/ListDef.pm
- src/lib/Sympa/Robot.pm
Fixed bugs:
- WWSympa: On list config page, default settings of list scenarios are ignored. And if user updated configuration, the first option in select box is saved.
Fixed by assigning defaults in Sympa::ListDef.
- `archive.web_access` list parameter did not have default value.
Change:
- The feature making a symbolic link "*.default" to assign default values of scenarios is deprecated.
It was hard to determine original option value linked to default.
> Invalid default scenarios

- src/cgi/wwsympa.fcgi.in
- src/lib/Sympa/ConfDef.pm
- src/lib/Sympa/List.pm
- src/lib/Sympa/Message.pm
- src/lib/Sympa/Request/Handler/create_automatic_list.pm
- src/lib/Sympa/Request/Handler/move_list.pm
- src/lib/Sympa/Request/Handler/update_automatic_list.pm
- src/lib/Sympa/Upgrade.pm
- src/lib/Sympa/WWW/Tools.pm
This may fix #507.
Fixes:
- [bug] Message footer/header files of domain/site default are put in `mail_tt2` subdirectories while those of list config are not.
Fixed by putting all of them in consistent location without intermediate directories (See also Notes below).
- [bug] Entries for header/footer files in `edit_list.conf` were ignored.
Changes:
- File names themselves of header/footer were changed:
`message_header`, `message_header.mime` etc.
This is due to consideration about conflict between files and directories with domain names (See also Notes below).
- [change] Header/footer files with `.mime` extension:
Previously, files with this extension were always preferred, then if they were not found, files without extension were used.  This behavior has not been documented.
Now files …
> Inconsistent location of messge footer/header files #507

- default/mail_tt2/report.tt2
- default/web_tt2/confirm_action.tt2
- default/web_tt2/pref.tt2
- src/cgi/wwsympa.fcgi.in
- src/lib/Sympa/ConfDef.pm
- src/lib/Sympa/List.pm
- src/lib/Sympa/Robot.pm
Only from web interface for now.
- add a form on pref page to delete the account
- checks the password of the user
- if it's good:
- unsubscribe the user from all its lists
- remove the user from the editor role of all its lists
- remove the user from owner role of all its lists *only* if he/she
is not the only owner (=> don't delete the account and give an error message)
- if he/she was the only privileged owner of a list, give privileged
profile to all unprivileged owners
> Fix #300 — Allow to delete your own account

- default/mail_tt2/request_auth.tt2
Even if web interface was disabled (wwsympa_url parameter was unset), mail URL link was not shown in confirmation requests for subscribe/unsubscribe actions.
Fixed by replacing test on an unassigned variable user_interfaces with test on conf.wwsympa_url.
> Mail command unavailable in confirmation requests

- src/lib/Sympa/List.pm
[bug] "Users" - "Owner" page is empty for a while after restart, as picture below.
Fixed by correcting typos not loading information soon.
> Owner page is empty

- support/README.support.md
- support/correct_msgid
- support/git-set-file-times
> Maintenance support scripts

- .gitignore
- Makefile.am
- configure.ac
- sympa.conf.in
Preparing minimal sympa.conf at install time.  `sympa_wizard.pl` will no longer be used to create it.
See #508.
> Prepare minimal sympa.conf at install time (cf. #508)

- src/lib/Sympa/Aliases.pm
- src/lib/Sympa/Family.pm
To prevent creation of list with reserved addresses, only sticked names `bounce@...` and `bounce+...@...` were prevented: `bounce_email_prefix` parameter was not considered.
> `bounce_email_prefix` parameter was not considered to prevent reserved addrresses for list name (PR#455)

- default/web_tt2/admin.tt2
- default/web_tt2/list_menu.tt2
- src/cgi/wwsympa.fcgi.in
- src/lib/Sympa/ConfDef.pm
- src/lib/Sympa/Upgrade.pm
* Even if `process_archive` parameter was "off", items about archiving were shown in web interface.
* Shared repository could not be disabled: List owners could freely install it.
This PR will fix those problems.
Especially on latter, a new parameter `shared_feature` in sympa.conf/robot.conf was introduced to enable/disable the feature of shared document repository.
> WWSympa: Features of archives and shared repository should be able to be disabled

- default/mail_tt2/listmaster_notification.tt2
- src/bin/upgrade_sympa_password.pl.in
- src/lib/Sympa/List.pm
- src/lib/Sympa/Tools/Password.pm
- src/lib/Sympa/User.pm
- src/lib/Sympa/WWW/Auth.pm
- src/lib/Sympa/WWW/SOAP.pm
- src/lib/Sympa/WWW/Session.pm
This PR abandon Crypt::CipherSaber.
* `sympa_session` cookie is no longer encrypted.
This change may make session cookie by earlier releases incompatible, if Crypt::CipherSaber has been used.
* RC4 encrypted password in user_table will no longer be supported.
Administrators upgrading from earlier versions have to run `upgrade_sympa_password.pl` to decrypt and to rehash older passwords.
This PR may fix #87.
> Deprecate CipherSaber RC4 encryption (#87)

- src/bin/sympa_test_ldap.pl.in
sympa_test_ldap: If `--bind_dn` was given but not `--bind_password`, password prompt is shown. However, input password was ignored.
> sympa_test_ldap.pl misses bind password

- src/lib/Sympa/Message.pm
> Crash with broken S/MIME user certificate (cf. #565)

- default/web_tt2/config_common.tt2
- default/web_tt2/d_control.tt2
- default/web_tt2/dump_scenario.tt2
- default/web_tt2/my.tt2
- default/web_tt2/suspend_request.tt2
- src/cgi/wwsympa.fcgi.in
- src/lib/Conf.pm
- src/lib/Sympa/List.pm
- src/lib/Sympa/Message.pm
- src/lib/Sympa/Request/Handler/get.pm
- src/lib/Sympa/Request/Handler/global_remind.pm
- src/lib/Sympa/Request/Handler/global_set.pm
- src/lib/Sympa/Request/Handler/global_signoff.pm
- src/lib/Sympa/Request/Handler/index.pm
- src/lib/Sympa/Request/Handler/info.pm
- src/lib/Sympa/Request/Handler/invite.pm
- src/lib/Sympa/Request/Handler/last.pm
- src/lib/Sympa/Request/Handler/lists.pm
- src/lib/Sympa/Request/Handler/which.pm
- src/lib/Sympa/Scenario.pm
- src/lib/Sympa/Spindle/AuthorizeMessage.pm
- src/lib/Sympa/Spindle/AuthorizeRequest.pm
- src/lib/Sympa/Spindle/ProcessBounce.pm
- src/lib/Sympa/Spindle/ProcessTask.pm
- src/lib/Sympa/Upgrade.pm
- src/lib/Sympa/WWW/SOAP.pm
- src/lib/Sympa/WWW/SharedDocument.pm
Fixed bug:
* Confusion between list parameter names and scenario function names. For example:
- If a compound parameter (e.g. `shared_doc.d_read`) is given, corresponding scenario (`d_read.xxx`) mistakenly tries to include header file with parameter name (`include.shared_doc.d_read.header`) instead of that with scenario function name (`include.d_read.header`).  Fixed by assigning correct identifier.
- `dump_scenario page` of wwsympa  doesn't work with scenarios corresponding to compound parameters (shared documents, archives, tracking).
This may fix #520.
Changes in code:
* Sympa::Scenario::request_action() function was replaced with Sympa::Scenario::authz() method.
Changes in behavior:
* `log_module` and `log_condition` parameters were deprecated.  They were not so useful.  Instead, …
> Refactor Sympa::Scenario (cf. #520)

- src/cgi/wwsympa.fcgi.in
Now it gets `rfc822Name` in X.509v3 `subjectAltName`, otherwise `emailAddress` attribute in subject DN (the first one of either), accroding to S/MIME (See [RFC 5750](https://tools.ietf.org/html/rfc5750), 3 and 4.4.3).
Note that earlier efforts getting attribute such as `MAIL`, `Email` in subject DN are no longer supported.
> WWSympa: TLS client authentication: Get email from certificate according to S/MIME

- src/lib/Sympa/Upgrade.pm
> Upgrade: A typo breaks configuration (#578)

- src/lib/Sympa/List.pm
When changing a list's admin two times in the same second, the list admins cache is not updated. Consequently, when trying to add a third admin in the same second, the second one is not in the cache at the time.
Obviously it does not sound like a recurrent scenario and I met this problem when running a test file only.
However, it is possible that this happens more often when trying to make batch modifications in the shell. And also, it made my test fail which is an engineering problem: it could be misguiding about the cause of a test failure.
So I changed the expiration test, replacing "<" by "<=" and it solves the problem.
I don't see any side problem that could result from this change bu I commit it separately anyway because the cache is very sensitive.
> Slight change in list admins cache expiry.

- cpanfile
- src/lib/Sympa/Message.pm
Fixed by parsing the field according to standards.
See #575.
> ARC: Comment in Authentication-Results field prevents check on srvid (See #575)

- src/lib/Sympa/Message.pm
`Mail::DKIM::Signer` wraps `DKIM-Signature` with with `\r\n\t`; this is the hardcoded `Separator` passed to `Mail::DKIM::TextWrap` via `Mail::DKIM::KeyValueList`. `MIME::Tools` on the other hand
(`MIME::Head::stringify()` in particular) encode EOL as plain `\n`; it is thus necessary to normalize CRLF->LF for `DKIM-Signature` to avoid confusing the mail agent.
Exim in particular handles line endings by observing [these rules](https://www.exim.org/exim-html-current/doc/html/spec_html/ch-message_processing.html#SECTlineendings) of interest:
> * If a bare CR is encountered within a header line, an extra space is added after the line terminator so as not to end the header line. The reasoning behind this is that bare CRs in header lines are most likely either to be mistakes, or people trying to …
> dkim_sign: Normalize CRLF->LF for DKIM-Signature

- src/lib/Sympa/Scenario.pm
We are upgrading from Sympa 6.2.36 to 6.2.42.
After upgrading our test staging instance of Sympa we encountered an error while editing the liste config through the web interface: 
```
DIED: Can't call method "get_current_title" on unblessed reference at /usr/local/sympa/bin/wwsympa.fcgi line 10847.
at /usr/local/sympa/bin/wwsympa.fcgi line 10847.
main::_do_edit_list_request(Sympa::List::Config <test-sympa-2-2-42@listes.univ-rennes1.fr>, HASH(0x59b0758), ARRAY(0x5bbf7e0)) called at /usr/local/sympa/bin/wwsympa.fcgi line 10771
main::do_edit_list_request() called at /usr/local/sympa/bin/wwsympa.fcgi line 1558
```
The log says:
```
Apr  8 10:35:40 vmperl-tsympa1 wwsympa[10736]: info main::do_edit_list_request(description) [robot listes.univ-rennes1.fr] [session 50683453466904] [client …
```
> Sympa::Scenario::new() was unable to load scenario filename including dots

- src/lib/Sympa/Aliases/Template.pm
This behavior is useless when aliases file is shared by multiple hosts with network drive.
Fixed by creating lock at the same place as aliases file.
> Sympa::Aliases::Template creates exclusive lock on local storage

- .gitignore
- Makefile.am
- configure.ac
- mk-sympa-dist.pl.in
- `sympa.conf-dist` always contains all available configuration settings, letting admins copy those they want in `sympa.conf`;
- it’s generated at `make`, getting the settings from `Sympa::ConfDef` module;
- it’s installed in `$sysconfdir` at `make install`.
> Add sympa.conf-dist

- src/lib/Sympa/Aliases/Template.pm
With fix on #593, NFS cache was not flushed when aliases file was opened.
Fixed by opening aliases file as Sympa::LockedFile instance.
Note: To keep exclusive processing by file lock effective, file won't be closed (unlocked) before newaliases will be finised.
> Additional fix to #593

- src/lib/Sympa/List.pm
In add_list_member the value $current_list_members_count is discarded if max_list_member == 0 (default setting).
This prevents the "high db load" produced by the successive DB accesses.
> Prevent unnecessary DB access in add_list_member

- default/web_tt2/confirm_action.tt2
- default/web_tt2/search_user.tt2
- src/cgi/wwsympa.fcgi.in
- src/lib/Sympa/List.pm
- src/lib/Sympa/ListDef.pm
- src/lib/Sympa/Scenario.pm
- Bulk unsubscribe is back (#27)
- Tidying some files
- The unsubscribe and edit buttons where not shown in search_user.tt2, they are back. I also change the name of the unsubscribe button that was "delete" and sounds confusing to "Unsubscribe the User" (already available in the translations)
- I added the list of users that will be bulk-unsubscribed from a list on the confirmation page (go to a list subscribers review page, select some of them, unsubscribe them => their addresses are listed on the confirmation page, as reminder).
> Fix #27 — Missing admin function to bulk unsubscribe

- default/web_tt2/review.tt2
- src/cgi/wwsympa.fcgi.in
- Currently, only light export is available, thus export doesn’t contain
the name of the subscribers. The button solves that.
- The full export always includes a header:
\# Exported subscribers with search filter ""
But it’s useless and maybe confusing when you use the full export from
the button. I removed that header if no filter was sent
- I changed an "unless defined" assignment to "//", I don't know if it’s
ok to do that.
> Add a button for full export of subscribers

- src/sbin/sympa.pl.in
> Fix #609 — Handle boilerplate db_type conf in sympa.pl --health_check

- src/lib/Sympa/Request/Handler/move_list.pm
> Fix #624 — Correctly rename archive folder when renaming list

- src/lib/Sympa/WWW/Marc/Search.pm
I think it’s a good fix for #613
> Fix #613 — Avoid MHonArc’s search warning flood

- src/lib/Sympa/ConfDef.pm
- src/lib/Sympa/HTMLDecorator.pm
- src/lib/Sympa/ListDef.pm
- src/lib/Sympa/ListOpt.pm
This allows to make web archives public without fearing to leak users
email addresses. This has only effect when you display a mail. In the archive list, the behavior is the current one: display gecos if any, display first part of email address otherwise (i.e. `foo` if the address is `foo@bar.org`).
Please note that I adapted the code from `decorate_email_at` subroutine.
Also, I used 'No gecos' as message when the email address didn’t contain a gecos, but feel free to propose somethin more easier to understand.
May fix #621
> Fix #621 — Add a 'gecos' option to web_archive_spam_protection

- src/lib/Sympa/Robot.pm
I didn’t have the same error described in #581 (`Unable to find scenario file "topics_visibility.conceal "`) but this one:
```
DIED: Can't call method "authz" on an undefined value at /home/sympa/bin/wwsympa.fcgi line 15627.
at /home/sympa/bin/wwsympa.fcgi line 15627.
main::export_topics('sympa.test.org') called at /home/sympa/bin/wwsympa.fcgi line 2755
main::check_param_in() called at /home/sympa/bin/wwsympa.fcgi line 1501
```
My patch fixes it, so it should work for #581
> Don’t capture extra spaces at the end of line in topics.conf

- src/lib/Sympa/Upgrade.pm
This may fix #652.
Spurious error message during upgrade from a version prior to 6.2b.1, if the directory /etc/sympa/web_tt2 does not exist.
> Improve handling of missing `sympa/web_tt2` during upgrade #652

- src/lib/Sympa/Request/Handler/add.pm
Fixes missing list name in output of the `sympa.pl --import` as reported in #656.
> Add list name to "is now subscriber of list" message.

- default/web_tt2/main.tt2
Fix #636
Adds an alert-box with the text "List not activated yet. Please wait until a listmaster activated it to be able to use it." below list subject.
> Make it clear on web interface that a list is being moderated

- src/lib/Sympa/List.pm
[bug] Since mtime for cache file like .last_change.admin on some filesystems like NFS with Linux was not updated.  Fixed by updating it explicitly with utime(), User pages will not be refreshed after update.
> mtime of file like .last_change.admin was not updated

- src/lib/Sympa/Spindle/ProcessTask.pm
task_manager.pl dies when the list no longer exist when some command such as sync_include was executed.
Fixed by checking if target list exists.
This may fix #681.
> task_manager.pl dies when the list no longer exist (#681)

- src/lib/Sympa/WWW/Auth.pm
As reported by Jacques Tissot on the mailing list:
```
DIED: [Tue Jul 23 08:47:54 2019] wwsympa.fcgi: Error on incoming parameter "$data", it must be a ref on HASH or a ref on ARRAY at /home/sympa/bin/Sympa.pm line 422.
at /usr/share/perl5/CGI/Carp.pm line 362.
CGI::Carp::realdie('[Tue Jul 23 08:47:54 2019] wwsympa.fcgi: Error on incoming pa...') called at /usr/share/perl5/CGI/Carp.pm line 461
CGI::Carp::die('Error on incoming parameter "$data", it must be a ref on HASH...') called at /home/sympa/bin/Sympa.pm line 422
Sympa::send_notify_to_listmaster('*', 'password_encrypted') called at /home/sympa/bin/Sympa/WWW/Auth.pm line 160
Sympa::WWW::Auth::authentication('unifr.ch', '<loginName>', '<password>') called at /home/sympa/bin/Sympa/WWW/Auth.pm line 60 …
```
> Fix crash of RC4 encrypted password notice.

- src/sbin/sympa.pl.in
- Small change to `--open_list` to let it handle pending lists
- Add `--show_pending_lists=robot` option to print pending lists (with some
informations)
Fix #637
> Allow to activate pending lists with sympa.pl

- default/web_tt2/edit.tt2
- default/web_tt2/edit_list_request.tt2
- default/web_tt2/editsubscriber.tt2
- default/web_tt2/help_admin-editlist-archives.tt2
- default/web_tt2/help_admin-editlist-bounces.tt2
- default/web_tt2/help_admin-editlist-command.tt2
- default/web_tt2/help_admin-editlist-description.tt2
- default/web_tt2/help_admin-editlist-other.tt2
- default/web_tt2/help_admin-editlist-sending.tt2
- default/web_tt2/help_admin-users.tt2
- default/web_tt2/help_user-suboptions.tt2
- default/web_tt2/review.tt2
- default/web_tt2/suboptions.tt2
Use 'Apply modifications' instead of 'Update' to make sure the changes/deletions will be effective only if update is performed.  These functions are subject to the change: `edit_list`, `editsubscriber/review/set` and `edit`.
This may fix #698.
> WWSympa: Use the label 'Apply modifications' instead of 'Update'

- src/cgi/wwsympa.fcgi.in
- src/lib/Sympa/Tools/Text.pm
Sympa::Tools::Text::wrap_text() consumes large amount of memory for large size of texts. Reduce it.
> Text wrapping consumes large amount of memory.

- default/mhonarc-ressources.tt2
- Attachment with long filename can break list archives
- Only us-ascii will be treated as-is.
This may fix #699
> Changes in mhonarc-ressources.tt2 (#699)

- support/pod2md
- Pod::Markdown 3.000 or better required.
- Enable `--release` option.
- Escape "`|`" to avoid bug on Jelyll converter which treats it as table.
> pod2md: Some fixes

- src/sbin/sympa.pl.in
I get this error while running 
```
$ sympa.pl -d --modify_list testfamily  --input_file /usr/local/sympa/list_data/testlist1/instance.xml
Can't use an undefined value as an ARRAY reference at /usr/local/sympa/bin/sympa.pl line 931.
```
I fixed `sympa.pl` to ensure `$result->{'string_info'} `and `$result->{'string_info'}` are defined before trying go through a `ARRAYREF`.
> Fix errors 'Can't use an undefined value as an ARRAY reference' while running sympa.pl --modify_list

- default/web_tt2/viewlogs.tt2
- src/lib/Sympa/Log.pm
When the user changes sorting order or goes to the next/previous page, action type selected previously will be reset.
> WWSympa: viewlogs: selected type of action is not preserved

- src/lib/Sympa/DataSource.pm
> Error message "Use of uninitialized value $2" while instancing family lists (#749)

- src/lib/Sympa/DataSource.pm
- src/lib/Sympa/DataSource/RemoteFile.pm
- src/lib/Sympa/DatabaseDescription.pm
- src/lib/Sympa/ListDef.pm
This fixes:
- a typo mislead by the fix for #693.
- lack of consideration about column size.
See also [a post on sympa-users](https://listes.renater.fr/sympa/arcsearch_id/sympa-users/2019-09/E830CF905957404CB59FAEF2A5FD302A01ADB335%40CNREXCMBX05P.core-res.rootcore.local).
> Additional fix to #693

- t/compile_executables.t
Test: compile_executables: Test::Compile 2.3.0 ignores *.fcgi files.
> Test: Supports recent version of Test::Compile

- src/lib/Sympa/Spool/Outgoing.pm
Sort recipients to be stored by domains.
This may fix #604.
> Make storage into outgoing spool more efficient (#604)

- src/lib/Sympa/DataSource/LDAP2.pm
Since 6.2.48, LDAP2 queries don't work anymore.
This is a simple and stupid patch to make it works.
> Patch for a working include_ldap_2level_query (#785)

- src/sbin/sympa.pl.in
Starting with: Fix typo in output from --sync_include commandline option.
More to come.
> Various improvements to --sync-include output

- cpanfile
IPv6 support needs Socket6 & IO::Socket::IP (or IO::Socket::INET6).
This may fix #784
> IPv6 support (#784)

- cpanfile
- src/lib/Sympa/Message/Plugin.pm
A mistake in a plugin module crashed sympa hard:
```
Nov 21 17:54:14 local-sympa sympa_msg[14599]: err main::#243 > Sympa::Spindle::spin#95 > Sympa::Spindle::TransformOutgoing::_twist#48 > Sympa::Message::Plugin::execute#61 > (eval)#1 > (eval)#1 > Sympa::Message::Plugin::BEGIN#1 DIED: Global symbol "$list" requires explicit package name (did you forget to declare "my $list"?) at /usr/local/lib/site_perl/Sympa/Plugin/DistributionNotification.pm line 24. Compilation failed in require at (eval 208) line 1.
Nov 21 17:54:14 local-sympa systemd[1]: sympa.service: Main process exited, code=exited, status=255/n/a
Nov 21 17:54:14 local-sympa systemd[1]: sympa.service: Unit entered failed state.
Nov 21 17:54:14 local-sympa systemd[1]: sympa.service: Failed with result 'exit-code'.
```
Justification …
> Prevent Sympa daemon crash due to a broken plugin module.

- .gitlab-ci.yml
- .travis.yml
- Makefile.am
- default/mail_tt2/listmaster_notification.tt2
- src/cgi/wwsympa.fcgi.in
- src/lib/Sympa/Scenario.pm
- t/compile_scenarios.t
Now scenarios will be precompiled to Perl coderef and cached on memory.  This change may make execution of scenarios fast.
Needs careful tests.
> Enhancements on scenarios

- src/lib/Sympa/List.pm
These log messages are not useful for normal debugging and are cluttering the logs unnecessarily.
> Demote Sympa::List debug messages when invoking constructor and load method

- cpanfile
- t/pod-syntax.t
Test: t/pod-syntax.t: Test::Pod 1.40 mistakenly complains about the construct L<text|url>. Use 1.41 or later.
> Updating dependency Test::Pod

- src/lib/Sympa/Scenario.pm
Scenario: Fixing a bug injected by #782. File names for search filters may not be quoted.
This may fix #813.
> Fixing #813

- src/lib/Sympa/Scenario.pm
This PR may prevent:
- the error on "Modification of non-creatable array value" by using "`[header->Field][-1]`" in scenarios.
- failure of scenario execution without required "message" parameter.
This may fix #831
> Scenario fails with negative indices in [header->Field][n] (#831)

- cpanfile
- src/cgi/wwsympa.fcgi.in
- src/lib/Conf.pm
- src/lib/Sympa/Request/Handler/create_list.pm
- src/lib/Sympa/Robot.pm
- src/lib/Sympa/Tools/Text.pm
- src/lib/Sympa/Upgrade.pm
- t/pod-syntax.t
Deprecate filesystem_encoding parameter which has already been fixed to utf-8.
Introduced Sympa::Tools::Text::slurp() to slurp text file applying Unicode sanitization and normalization. Note: Though Unicode::Normalize and Unicode::UTF8 are optional now, they would be mandatory in the future.
> Deprecate filesystem_encoding parameter

- src/sbin/sympa.pl.in
See related mailing list post "Welcome message when importing users".
> Prevent welcome emails on import with --quiet.

- default/mail_tt2/listmaster_notification.tt2
- default/mail_tt2/listowner_notification.tt2
- default/mail_tt2/moderate.tt2
- src/lib/Sympa.pm
- src/lib/Sympa/List.pm
- src/lib/Sympa/Spindle/ToModeration.pm
This may fix (partly) #156: This deprecates some of one-time ticket feature.
- `get_pending_list` action in notification about created/renamed lists for listmaster.
- `search` action in notification about failed unsubscriber for list owner.
- `modindex` action in notification about held messages for list moderator.
Now actions above need authentication on web interface.
On the other hand:
- ~~`family_signoff` action: Since this action has never been documented nor completely implemented, **it will be removed**.~~ `family_signoff` is documented.  It should be rewritten not to use one-time ticket.
- `sso_login/confirmemail` action ditto.
- `choosepasswd` action ditto.
> Deprecate one time ticket (1) (#156)

- .travis.yml
- src/lib/Sympa/Message.pm
- t/Message.t
- t/data/list_data/test/config
- t/samples/urlize-deep-nested-mixed.eml
- t/samples/urlize-encoding.eml
- t/samples/urlize-nested-alternative-and-related.eml
- t/samples/urlize-nested-alternative.eml
- t/samples/urlize-nested-mixed.eml
- t/samples/urlize-nested-mutiple-attachments.eml
- t/samples/urlize-simple-mutiple-attachments.eml
- t/samples/urlize-simple.eml
- t/stub/Sympa/Constants.pm
Fixing bugs in urlize mode : 
1- message text was treated as attachment and remained on the server as either "msg.0.bin" or "msg.0.txt" files. Fixed by testing the part type before urlizing it.
2- some special characters in message id led to the attachment to be considered missing by Sympa.
I also introduce a test file for Message.t, testing only urlization. this test is set in travis and the test succeeds. Note that commits 065312d and fcadbac are related to travis. The first one to enable the test, the second one to have Sympa::Constants without running make.
> Urlize mode bug fixes

- src/lib/Sympa/Message.pm
If the messages signed with PGP/MIME was posted, unuseful error messages are shown in syslog.
This may fix #867.
> Unreasonable error message to notify broken signature with PGP/MIME messages

- src/lib/Sympa/List.pm
This may fix #866 
Comment: This bug has been injected on 6.2.45beta.
> Unable to sort column in subscriber list (#866)

- src/cgi/wwsympa.fcgi.in
- src/lib/Sympa/Message.pm
- t/Message_urlize.t
An insignificant bug.
Discouraged `Sympa::Tools::Text::escape_chars()` was used in the name of file stored for URLize mode.
> URLize: Use filesystem-independent escaping for names of files stored

- src/cgi/wwsympa.fcgi.in
- src/lib/Sympa/Message.pm
* URLize: If personalization was enabled, urlization is prevented.  Because directory for attachment files will have been created by test_personalize() and can't be created again.
* Suppress unuseful logs skipping urlization of attachments with Content-Disposition.
* WWSympa: do_attach(): Avoid urlized attachments to be rendered by the browser.
> Some bugs related to urlize mode

- src/lib/Sympa/ConfDef.pm
- src/lib/Sympa/WWW/FastCGI.pm
This PR is based on #910.
Though the `http_host` parameter has been obsoleted, many site may set this parameter as the same as host part of `wwsympa_url` and they may have to remove it (e.g. see [a post on dev list](https://listes.renater.fr/sympa/arcsearch_id/sympa-developpers/2020-03/cef874de-1935-36d2-fa46-0b6ac8c309d8%40linuxia.de)).
Instead of keeping this complicating parameter, we'd be better to introduce the new `wwsympa_url_local` parameter to specify proxy upstream URL.
> Replace `http_host` parameter with `wwsympa_url_local` parameter (addition to #910)

- src/lib/Sympa/ListDef.pm
Fix: `spam_protection` list paramter did not derive its default from the same paramter in `robot.conf`/`sympa.conf`.
> `spam_protection` list paramter did not derive its default from robot/site config

- src/cgi/wwsympa.fcgi.in
This is a simple commit to fix the issue. The code for `do_editfile` could be improved further. Especially the following code doesn't make sense as it is called *after* the file contents have been slurped:
```
if (-f $param->{'filepath'} && (!-r $param->{'filepath'})) {
Sympa::WWW::Report::reject_report_web('intern', 'cannot_read',
{'filepath' => $param->{'filepath'}},
$param->{'action'}, '', $param->{'user'}{'email'}, $robot);
wwslog('err', 'Cannot read %s', $param->{'filepath'});
web_db_log(
{   'parameters' => $in{'file'},
'status'     => 'error',
'error_type' => 'internal'
}
);
return undef;
}
```
> Fix missing content for listmaster admin template edits in the web interface

- src/lib/Sympa/List.pm
- src/sbin/sympa.pl.in
One minor fix to handle errors when running `sympa.pl --instantiate_family`
The other is more important for us because it makes our Sympa GUI almost unusable because of horrible performances on global functions (/lists mainly).
> 2 fixes related to list families

- src/cgi/wwsympa.fcgi.in
For some background information, we're running Sympa 6.2.54 in a 
RHEL 7 environment. We've got around 6,000 lists and close to 
770,000 subscribers. 
Since upgrading to Sympa 6.2 about two years ago, we've come across 
a performance issue when an authenticated user uses the "list index" 
page (the /sympa/lists URI) to view all lists they have access to 
see. This page can take quite a while to load for an authenticated 
user (30-45 seconds). 
Digging around in the code, it appears the reason it takes a long 
time for this page to load in our environment is that there is a 
database lookup on a per list basis to check whether or not the user 
is either a privileged owner, owner, editor or subscriber. This 
lookup has become expensive for us due to the large number of active 
lists we have …
> list index performance update for wwsympa.fcgi do_lists subroutine

- configure.ac
- src/cgi/Makefile.am
- src/cgi/sympa_soap_server-wrapper.fcgi.c
- src/cgi/wwsympa-wrapper.fcgi.c
- src/libexec/Makefile.am
- src/libexec/sympa_newaliases-wrapper.c
This may fix #943 .
- Setuid wrappers should clear environment variables to avoid exploits. Clear environment varialbes.
- configure: Add options --disable-setuid_fcgi & --disable-setuid_queue.
> [SA 2020-002] Security flaws in setuid wrappers (#943)

- src/lib/Sympa/DataSource/SQL.pm
Obviously the issue was introduced back in 2015, as mentionned in https://listes.renater.fr/sympa/arc/sympa-users/2015-12/msg00002.html.
Here is an example of the issue :
```
/usr/local/sympa/bin/sympa.pl --sync_include=mylist-with-included-members@listes.etudiant.univ-rennes1.fr
...
Use of uninitialized value $value in printf at /usr/local/sympa/bin/Sympa/DataSource/SQL.pm line 91, <GEN1> line 1.
Use of uninitialized value $value in printf at /usr/local/sympa/bin/Sympa/DataSource/SQL.pm line 91, <GEN1> line 1.
Use of uninitialized value $value in printf at /usr/local/sympa/bin/Sympa/DataSource/SQL.pm line 91, <GEN1> line 1.
include [notice] Subscribers were included from data source "mysource" into list mylist-with-included-members.
include [notice] Inclusion succeeded (69 added, 15 …
```
> Every time users were loaded via include_sql_query Sympa would raise warnings

- default/Makefile.am
- default/mail_tt2/delivery_status_notification.tt2
- default/mail_tt2/listeditor_notification.tt2
- default/mail_tt2/shared_moderate.tt2
- src/cgi/wwsympa.fcgi.in
- src/lib/Sympa.pm
- src/lib/Sympa/List.pm
- src/lib/Sympa/Request/Handler/create_automatic_list.pm
- src/lib/Sympa/Request/Handler/create_list.pm
- src/lib/Sympa/Request/Handler/include.pm
- src/lib/Sympa/Request/Handler/move_list.pm
- src/lib/Sympa/Request/Handler/review.pm
- src/lib/Sympa/Request/Handler/update_automatic_list.pm
- src/lib/Sympa/Spindle/DoForward.pm
- src/lib/Sympa/Spindle/ToEditor.pm
- src/lib/Sympa/Spindle/ToList.pm
- src/lib/Sympa/Spindle/ToModeration.pm
- src/lib/Sympa/Upgrade.pm
- src/lib/Sympa/WWW/SOAP.pm
- src/sbin/sympa.pl.in
- review: Won't process sync_include in advance so that processing will be faster.
sync_include just before message delivery will be performed as in the past.
- sync_include will no longer be invoked during Sympa::List->new():
- No owner defined in a list is no longer treated as error_config.
- Instead, if no owner defined and something has to be sent to owners,
- If possible, discard incoming message and send back DSN to original sender,
- or, notifications to owners will be redirected to listmaster(s).
This may improve speed of "review" page and so on.
Also, this may fix #92 .
> Deprecate implicit sync_include in Sympa::List constructor

- src/lib/Sympa/List.pm
> Cannot include privileged owner from list even if it has to (#969)

- src/lib/Sympa/Message.pm
> ARC::Signer died because of a malformed "Authentication-Results:" header field (#988)

- src/sbin/sympa.pl.in
Relative to #993: with this option, we can rebuild all archives with a simple `for` bash loop, without restarting from beginning if `archived.pl` restarts while rebuilding all lists.
> sympa.pl: Add an option "--rebuildarc=list@domain" to rebuild archives

- src/lib/Sympa.pm
- src/lib/Sympa/Spindle/ProcessIncoming.pm
- src/lib/Sympa/Spool.pm
<sympa-request> address should not be forwarded to any functions of Sympa.  To avoid mail loop by such misconfiguration, discard messages bound for this address.
This may fix #957 .
> Mail loop with sympa-request address because of misconfiguration (#957)

- src/cgi/wwsympa.fcgi.in
The page was not listing the current list owners/editors because they were loaded the wrong way $list->{'admin'}{'owner'} instead of $list->get_current_admins. I was alerted by a listmaster who was surprised that this page still mentioned list owners.
I guess old list owners were loaded from a config.bin file.
> Fix get_inactive_lists

- src/lib/Sympa/Message.pm
As of Postfix 2.3, Content of Return-Path: pseudo-header field added by pipe(8) for null envelope sender became "MAILER-DAEMON".  Empty `null_sender` option will prevent this behavior.
As a workaround, the uppercase "<MAILER-DAEMON>" will be treated as null envelope sender.
This is a workaround for #1018 .
> Workaround for mail loop for sympa-request address (#1018)

- src/lib/Sympa/DatabaseDriver/MySQL.pm
MySQL: With MySQL 5.6, 5.7.6 and later versions, `sql_mode` system variable contains `STRICT_TRANS_TABLES` by which some obsoleted columns such as `date_admin` causes "(42000) Invalid default value for '_column name_'" error.  Fixed by resetting `sql_mode` to be empty, the default on 5.5.x or earlier.
This may fix #1028 .
> MySQL: (42000) Invalid default value

- cpanfile
- src/sbin/sympa_wizard.pl.in
See also sympa-community/MHonArc#7
> Update a dependency MHonArc

- src/cgi/wwsympa.fcgi.in
Currently, if you want to report archived mail(s) as spam while asking for deletion, the confirmation page is shown twice (only once if not reporting as spam). It appears like a bug to users.
This commit remove the confirmation when reporting as spam (there is still the confirmation for the deletion).
> 🐛 — Fix confirmation for reporting as spam while deleting an archived mail

- default/mhonarc-ressources.tt2
- default/web_tt2/confirm_action.tt2
- default/web_tt2/css.tt2
- src/cgi/wwsympa.fcgi.in
I think it would be good to have a reminder of which archived mails are about to be deleted (just like the reminder of the subscribers who are about to be unsubscribed), so here it is.
> Show subjects of archived mails before deletion’s confirmation

- src/lib/Sympa/Aliases/Template.pm
- src/lib/Sympa/Config/Schema.pm
This allows you to invoke the command from "sendmail_aliases" without using the wrapper. This should fix #946 and should work for Exim and Postfix MTA in most cases.
Current default is to use the alias wrapper, but in the future we may change that default.
> Add "aliases_wrapper" configuration parameter

- src/lib/Sympa/Aliases/Template.pm
Additional fix to #1015. 
Don't try to invoke the setuid wrapper sympa_newaliases-wrapper if it has been removed.
> Additional fix to #946 (#1015)

- src/lib/Sympa/DatabaseDriver/LDAP.pm
This is really helpful to figure out what went wrong with the connection to the LDAP server.
> Add actual error to the log if connection to LDAP server fails.

- src/lib/Sympa/WWW/SOAP.pm
Fix the defects in the current check:
- Allows bogus session id
- Allows session id which belongs to different user
May fix #1041.
> Properly check email and session id in authenticateAndRun SOAP call (#1041)

- default/web_tt2/compose_mail.tt2
Otherwise the legend describing the available TT2 parameter doesn't show up. This needs to be mentioned in the upgrade documentation as well.
> Adjust compose_mail template to the obsolescence of the merge_feature configuration parameter

- src/lib/Sympa/Spindle/ProcessOutgoing.pm
This should fix #1066. Tested with web and email using `footer_type append`.
It is likely that if works for the other possible scenarios as well.
> Fix regression in personalization feature (#1066)

- NEWS.md
- configure.ac
See also [the related discussion](https://github.com/orgs/sympa-community/teams/everyone/discussions/18).
> Release 6.2.60

- .gitlab-ci.yml
- .travis.yml
- cpanfile
- src/lib/Sympa/Tools/Text.pm
> Drop support for Perl prior to 5.16 (#1030)

- src/lib/Sympa/Config/Schema.pm
- src/sbin/sympa_newaliases.pl.in
This fixes an annoying error message. The problem is more or less cosmetic as the aliases are already probably updated.
```
~$ sympa --close_list test
err main::#144 Invalid aliases_program "none"
close_list [notice] List has been closed
```
Sympa version:  6.2.59b.2
Relevant configuration:
```
sendmail_aliases /etc/mail/sympa/aliases
alias_manager Template
aliases_program none
aliases_wrapper off
```
> Skip execution of aliases_program in newaliases script if value is "none"

- src/lib/Sympa/Config/Schema.pm
- src/lib/Sympa/HTMLDecorator.pm
- src/lib/Sympa/ListOpt.pm
- src/lib/Sympa/Template.pm
`web_archive_spam_protection gecos` didn't work because this option was omitted.  This PR may fix #1107 .
This PR includes the other fixes:
- Previously email addresses in HTML tags were not removed.
- The option name "gecos" is not so generally used. "concealed" looks more common.
> `web_archive_spam_protection gecos` didn't work as expected

- default/web_tt2/login.tt2
- default/web_tt2/renewpasswd.tt2
- src/cgi/wwsympa.fcgi.in
- However, this cannot prevent heuristics by Google Chrome: See #1033 .
> Add autocomplete="off" to all forms unless explicitly enabled.

- src/lib/Sympa/Config/Schema.pm
This prevents confusion seen at:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=929157#15
https://github.com/sympa-community/sympa/issues/876#issuecomment-590156276
Even better to have a format that checks whether it is a valid URL.
E.g. by feeding it to the URI module and verify that all vital parts
are present.
> Make it clear that wwsympa_url needs to include the protocol

- default/scenari/subscribe.owner
- default/scenari/unsubscribe.owner
There is no point to force the list owner to approve its own subscription and unsubscription to a list.
> Skip approval for owner subscription and unsubscription

- support/xgettext.pl
Since xgettext.pl processed TT2 templates as Perl source, a fake entry in PO file was generated.
> xgettext.pl: Templates shouldn't be processed as Perl source

- support/xgettext.pl
This fixes the bug injected by #1143 .
> Fix injected bug that xgettext.pl couldn't work with Perl 5.26 or later.

- src/lib/Sympa/Tools/Text.pm
Fix to #1106: A typo in POD of Sympa::Tools::Text.
This will be merged soon.
> Fix to #1106

- default/mail_tt2/report.tt2
- src/lib/Sympa/Aliases.pm
- src/lib/Sympa/ConfDef.pm
- src/lib/Sympa/Request/Handler/create_list.pm
- Add prohibited_listnames setting (comma-separated list, with ability
to use a wildcard)
- Add prohibited_listnames_regex setting
The settings are cumulative. You can use one or the other or both.
May fix #672
> Add ability to forbid some list names

- src/lib/Sympa/List.pm
See also https://listes.renater.fr/sympa/arc/sympa-fr/2020-11/msg00040.html for details.
> Empty paragraph in list config should not be warned.

- src/lib/Sympa/Message.pm
> Newlines in header fields added by ARC feature should be normalized (#1168)

- src/cgi/wwsympa.fcgi.in
- src/lib/Sympa/Archive.pm
- src/lib/Sympa/List.pm
- src/lib/Sympa/Message.pm
- src/lib/Sympa/Spindle/ProcessTask.pm
- src/lib/Sympa/Tools/Text.pm
- src/lib/Sympa/Tracking.pm
- src/lib/Sympa/Upgrade.pm
Since escape_chars() / unescape_chars() in Sympa::Tools::Text are wierd conversions and they are not filesystem safe, they'd be better to be replaced with encode_filesystem_safe() / decode_filesystem_safe().  This PR will do it.
> Obsolete escape_chars() / unescape_chars()

- default/web_tt2/info.tt2
- default/web_tt2/my.tt2
- default/web_tt2/suspend_request.tt2
- src/cgi/wwsympa.fcgi.in
Additional fix to #1176: Refactoring.  Deprecate is_user_allowed_to() tt2 function.
>  Hide archive download link from users without proper permissions #1176

- default/web_tt2/info.tt2
Don't show this link on the list info page when access would be denied anyway.
> Hide archive download link from users without proper permissions

- src/lib/Sympa/DataSource.pm
- src/lib/Sympa/Database.pm
- src/lib/Sympa/DatabaseDriver.pm
- src/lib/Sympa/DatabaseDriver/SQLite.pm
- src/lib/Sympa/List.pm
- src/lib/Sympa/Request/Handler/include.pm
**[Note by admin]** Please visit #1186 for discussion.
----
I've been looking into improving the performance of synchronizing members from data sources. I moved a couple of queries outside of loops and enabled transactions for the insert/update/remove loops.
This PR currently work in progress. It is lacking some error handling and it fails with SQLite, because of the current SQLite locking workaround.
I would like comments if this type of changes would be acceptable and suggestions for improvements!
| |Before | After |
|-|-------|-------|
|Time (sec)| 263 | 67.2 |
| Calls to do_prepared_query |240 032 | 120 032  |
| |Before | After |
|-|-------|-------|
|Time (sec)| 569| 141|
| Calls to do_prepared_query |580 032 | 260 032 |
> Data source synchronization performance improvement

- doc/sympa_config.podpl
- src/lib/Conf.pm
- src/lib/Sympa/Config/Schema.pm
- src/lib/Sympa/Upgrade.pm
This is the second work of refactoring. The final goal is improving the code to manipulate list/domain/site configuration in uniform method.
In this phase:
- Added not_before and not_after keys to hold available versions.
- Simplified Conf.pm handling paremeter name aliases a bit.
- Parameter "tracking" in sympa.conf/robot.conf will be forced renaming.
See also:
- (1) #924
> Refactor internals of config (2)

- default/web_tt2/my.tt2
- src/cgi/wwsympa.fcgi.in
If _set_my_lists_info() counts outstanding moderation requests for each list, then this information can be displayed by the my.tt2 template.
> Count messages in moderation queue for each list

- src/sbin/sympa.pl.in
In the sympa.pl CLI we have the "import" option to add subscribers to a list, but we lack a similar command to remove subscribers from the list.
This command is useful if you need to remove subscribers from a batch script
> Add unsubscribe command to remove emails from list in sympa.pl

- src/lib/Sympa/Config/Schema.pm
Hopefully the final occurrence in the sources :grimacing:
> Fix outdated "intranet" sample in create_list schema description.

- src/lib/Sympa/List.pm
- src/lib/Sympa/Request/Handler/close_list.pm
Change calling convention of Sympa::List::delete_list_admin() to avoid misuse.
This may fix #1272.
> Included owners won't be removed even if they have been removed from the data source (#1272)

- cpanfile
- src/sbin/sympa.pl.in
* Missing Gertopt::Long in cpanfile
* And sympa.pl needs configure options for it
This may fix #1251 more.
> More fix for #1251

- src/lib/Sympa/Request/Handler/move_list.pm
If creating a new list as copy of an existing one then this should also 
1. copy multipart mime footer/header (*.mime files)
2. copy template directories 
The fix (PR) does this by adding both *.mime files to the list of file.
And by fixing the copy logic to also copy template directories.
> fix: create a list as copy does not copy all configuration (template files)

- src/cgi/wwsympa.fcgi.in
> Listmaster Admin's menu entry "Edit Robot Config" missing when in "Skins, CSS and colors" (#1291)

- t/Tools_File.t
Version
-------
Sympa 6.2 or later with some platforms (e.g. macOS with Perl prior to 5.32 and LLVM).
Installation method
-------------------
Source distribution.
Expected behavior
-----------------
Running `make check`, tests shouldn't fail.
Actual behavior
---------------
With `t/Tools_File.t`, the test crashes with the message:
``` code
Error: The futimes function is unimplemented at t/Tools_File.t line 139.
t/Tools_File.t ............... 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 4/23 subtests 
```
Additional information
----------------------
Some platforms miss or simply don't implement futimes system call so that calling utime() on filehandle may crash.
This bug affects only to the test suite: The runtime code doesn't call utime() in such way.
> macOS: t/Tools_File.t fails.

- Makefile.am
PERL5LIB environment variable is overwritten when test harness is called so that customized module path (e.g. by local::lib) became unavailable.
> PERL5LIB environment variable was overwritten

- .github/workflows/make-check.yml
Adding GitHub Actions workflow for automated testing.
---
This PR depends on #1288 & #1299 .
> Adding the workflow for automated testing

- .github/workflows/make-check.yml
Crypt::OpenSSL::X509 has not supported openssl@3 that is installed on recent macOS by default.
Fix to #1287.
> workflow/make-check.yml: Jobs for macOS are tentatively disabled

- src/lib/Sympa.pm
- src/lib/Sympa/Config/Schema.pm
- src/lib/Sympa/Message/Template.pm
- src/lib/Sympa/Request/Handler/get.pm
- src/lib/Sympa/Request/Handler/last.pm
- src/lib/Sympa/Request/Handler/modindex.pm
- src/lib/Sympa/Spindle/ProcessDigest.pm
- src/lib/Sympa/Spindle/TransformIncoming.pm
- src/lib/Sympa/Spool/Listmaster.pm
- src/lib/Sympa/Spool/Topic.pm
* Remove more header fields in anonymized messages, including User-Agent.
* Use more precise number in auto-generated message IDs to prevent collision more.
* Use sufficiently unique message ID above in the anonymized messages.
This may fix #1306 .
> Improvements on anonymized messages

- default/web_tt2/confirm_action.tt2
- default/web_tt2/css.tt2
It adds a list (`<ul><li>…`) of the names of the lists that will be purged on the confirmation page.
> Show list names when purging closed lists

- src/lib/Sympa/List.pm
- src/lib/Sympa/Upgrade.pm
During upgrade from Sympa prior to 6.2b.1, some parameters in list config files can be removed: `include_file` (supposed to be converted to `include_sympa_list`, though) and po9ssiblly `archive`.
---
This PR may fix #1321.
> Upgrade: some parameters in list config files may be removed

- src/lib/Sympa/Database.pm
- src/lib/Sympa/DatabaseDriver/SQLite.pm
As most of RDBMS do not support nested transactions, only the outermost transaction should be available.
This may fix #1330 .
> Database: Nested transaction crashes

- default/mail_tt2/report.tt2
- src/lib/Sympa/Request/Handler/open_list.pm
When opening pending list, we have a notification `Aliases have been installed.` but it may be useful to have a reminder of the list we opened (when mass opening the pending lists, for ex.).
> Remind name of the opened list in the notification

- src/lib/Makefile.am
- src/lib/Sympa/CLI/bouncers.pm
- src/lib/Sympa/CLI/bouncers/del.pm
- src/lib/Sympa/CLI/bouncers/reset.pm
- src/lib/Sympa/CLI/review.pm
- src/lib/Sympa/List.pm
- src/lib/Sympa/Request/Handler/del.pm
- src/sbin/sympa.pl.in
Fix #1058 
I’m not sure about the `--show_status_of_members`: I print differently users with `bounce` attribute, users with `suspend` attribute and all the others. Is `suspend` attribute a sign of an error? Should I just print the `ok` and `bounce` users?
What are your thoughts about it?
> ✨ — Add "bouncers reset", "bouncers del" and "bouncers [--status] review" commands to sympa.pl

- default/web_tt2/arcsearch_form.tt2
- default/web_tt2/confirm_action.tt2
- default/web_tt2/d_properties.tt2
- default/web_tt2/review.tt2
- default/web_tt2/scenario_test.tt2
Therefore, clicking on the label did not change the state of the checkbox.
> 🐛 — Missing some id on input tags

- src/cgi/wwsympa.fcgi.in
WWSympa: When the last data source has been removed and included user(s) remain, [Synchronize ... with data sources] button is no longer shown.
This may fix #1355.
> WWSympa: "Synchronize ... with data sources" button is not shown (#1355)

- default/mail_tt2/report.tt2
- src/lib/Sympa/List.pm
- src/lib/Sympa/Request/Handler/add.pm
- src/lib/Sympa/Request/Handler/del.pm
- src/lib/Sympa/Request/Handler/include.pm
- src/lib/Sympa/Request/Handler/signoff.pm
- src/lib/Sympa/Request/Handler/subscribe.pm
> Fix #533 — Prevent the use of the list address as subscriber

- src/lib/Sympa/WWW/Marc/Search.pm
> WWSympa: File paths of archived messages may be exposed in the result of arcsearch (#1364)

- default/web_tt2/user_menu.tt2
As discussed in #1393, this PR removes the menu entries showing only information. These provide no target and cause layout problems.
> Remove user menu entries showing only information (#1393)

- default/web_tt2/info.tt2
> The owner sees the pop-up stating a message is waiting for moderation even if moderators are defined separately (#1406)

- src/lib/Sympa/WWW/SOAP.pm
> SympaSOAP: Result by setCustom with parameter including non-ASCII characters is broken (#1407)

- cpanfile
- default/web_tt2/compose_mail.tt2
- default/web_tt2/ls_templates.tt2
- default/web_tt2/review.tt2
- default/web_tt2/skinsedit.tt2
- src/cgi/wwsympa.fcgi.in
- src/lib/Sympa/Config/Schema.pm
- support/xgettext.pl
> Fix some typos

- src/lib/Sympa/Message.pm
This may fix #1454.
This bug looks injected on Sympa 4.2b.3: cf. sympa-community/historic-sympa@7674013
> Crash with the broken message with "multipart/signed" MIME type (#1454)

- .github/release.yml
- .github/workflows/make-check.yml
- .github/workflows/submit-pr-for-translation.yml
I wrote a script that is regularly running on the translation server to push the update of translations.
This PR adds a new GitHub Actions workflow to submit the PR necessary to merge pushed changes above.
It also adds a new label "ignore-for-release" to exclude PRs from the automated release notes (check [the doc](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes)).
> Adding GH workflow to submit the PR for translation

- cpanfile
- src/lib/Sympa/Message.pm
This PR follows fix of a non-fatal typo in Mail::DKIM::ARC::Signer: marcbradshaw/mail-dkim#3 .
> Following typo fix in Mail::DKIM::ARC::Signer

- cpanfile
- src/lib/Sympa/Config/Schema.pm
- src/lib/Sympa/Message.pm
- src/lib/Sympa/Regexps.pm
- src/lib/Sympa/Spindle/ProcessAutomatic.pm
- src/lib/Sympa/Spindle/ProcessIncoming.pm
- src/lib/Sympa/Tools/DKIM.pm
See [discussion](https://github.com/sympa-community/sympa/issues/1450#issuecomment-1192163883) on #1450.
> ARC: Add Authentication-Results: field (AR), if useful one is not found

- src/lib/Sympa/Spindle/DoForward.pm
DoForward: Messages forwarded via listmaster/owner/editor address should be ARC sealed if possible (As the messages won't be modified, DKIM signature may not be added).  See also discussion on #1450.
This PR depends on PRs #1452 & #1453,
> Forwarded messages should also be ARC sealed if possible

- src/lib/Sympa/Database.pm
Loading CSV driver crashes, because customizing `$SIG{__DIE__}` by Sympa::Crash breaks processing in File::stat .
This may fix #1434.
> Loading CSV driver crashes

- default/sympa.wsdl
This fix adds the required import of the SOAP encoding schema in WSDL so clients don't have to [deal with a broken schema](https://github.com/suds-community/suds#fixing-broken-schemas).
> Import SOAP encoding schema in WSDL

- default/edit_list.conf
- src/lib/Sympa/Config/Schema.pm
- src/lib/Sympa/List.pm
- src/lib/Sympa/ListOpt.pm
- t/data/sympa.conf
* Rename `welcome_return_path` & `remind_return_path` to `verp_*`.
* Rename their options "owner" & "unique" to "off" and "on".
This may fix #1475.
> Options for welcome_return_path & remind_return_path do not describe their function (#1475)

- src/lib/Sympa/Message/Template.pm
This may fix #1494.
This bug was injected on 6.2a.41: cf. sympa-community/historic-sympa@178f0a8
> Templates couldn't access to the fields defined by db_additional_subscriber_fields parameter

- src/cgi/wwsympa.fcgi.in
- src/lib/Conf.pm
By this PR. the new "cgi" paragraph(s) may be added in `auth.conf`:
```  code
cgi
auth_scheme Basic
remote_user_variable REMOTE_USER
regexp @my[.]dom[.]ain
negative_regexp evil@user[.]net
```
All parameters are optional.
- `remote_user_variable` (default value is `REMOTE_USER`) is the name of CGI variable providing e-mail of the authenticated user.
- If `auth_scheme` is specified, authentication is available only when the value of `AUTH_TYPE` CGI variable matches it.
This is a candidate of changes aim at fixing #1497.
> WWSympa: New "cgi" authentication simply using credentials provided by HTTP server

- src/lib/Sympa/Config/Schema.pm
Added fields for ARC (RFC 8617: `ARC-Authentication-Results`, `ARC-Message-Signature`, `ARC-Seal`) and obsoleted Domainkey (RFC 4870: `Domainkey-Signature`).
> Update default of anonymous_header_fields parameter

- default/mail_tt2/moderate.tt2
mail templates: If web interface is available, use it for command links.
This may fix #1124 (against the case with Outlook for Mac).
> `mailto:` link cannot be detected by some MUAs (#1124) [2]

- default/mail_tt2/delivery_status_notification.tt2
- default/mail_tt2/message_report.tt2
- src/lib/Sympa.pm
- src/lib/Sympa/Spindle/ToEditor.pm
- src/lib/Sympa/Spindle/ToModeration.pm
The report "Your message ... has been forwarded to the moderator(s)" may be sent as DSN.  This is not a notification that must be received always.
This may be related to #1354.
> Use DSN for the message to notify moderation

- default/edit_list.conf
- default/web_tt2/config_common.tt2
- src/lib/Sympa/Config/Schema.pm
- www/js/sympa.js
One more alternative to #877 , #898.
This may fix #872 .
> Skip edit for shared document options when disabled (#872) [3]

- src/lib/Sympa/DatabaseDriver/SQLite.pm
It seems that "occasionally" the SQL schema types in SQLite are not lower case so the upgrade in this case fail.
This patch was submitted in the following bug report: https://bugs.debian.org/1022943
> Fix SQLite upgrade with lowercase types

- NEWS.md
- doc/sympa_config.podpl
- src/cgi/wwsympa.fcgi.in
- src/lib/Sympa.pm
- src/lib/Sympa/CLI/show_pending_lists.pm
- src/lib/Sympa/DataSource.pm
- src/lib/Sympa/Family.pm
- src/lib/Sympa/List.pm
- src/lib/Sympa/Message.pm
- src/lib/Sympa/Message/Plugin.pm
- src/lib/Sympa/Tools/Data.pm
- src/sbin/sympa.pl.in
- support/xgettext.pl
Some of theses typos are present in man pages.
> Fix various typos in source comments

- src/lib/Sympa/Request/Handler/include.pm
**Now under self review**
Inclusion: When all of the data sources are skipped by nosync_time_ranges, log notes failure of inclusion.
This may fix #1429 .
> Inclusion: log mistakenly notes failure of inclusion

- src/lib/Sympa/CLI/config.pm
While trying to update a config value using `sympa config` command when there are no changes, it die() with a return code > 0.
It means that the command is not idempotent.
As an example, we started to use it in Debian Maintainer scripts with some config parameters instead of our custom routines to update configuration.
> Fix 'sympa config' command return code to be 0 when there are no changes

- src/cgi/wwsympa.fcgi.in
- src/lib/Sympa/DatabaseDriver.pm
- src/lib/Sympa/DatabaseDriver/ODBC.pm
- src/lib/Sympa/DatabaseDriver/Oracle.pm
- src/lib/Sympa/DatabaseDriver/SQLite.pm
- src/lib/Sympa/List.pm
- src/lib/Sympa/Message.pm
- src/lib/Sympa/Spindle/ProcessOutgoing.pm
- src/lib/Sympa/Spindle/TransformOutgoing.pm
This PR adds [RFC 8058 One-Click Unsubscribe](https://datatracker.ietf.org/doc/html/rfc8058) functionality.
The header fields for one-click are added to messages delivered through the list when the following conditions are met:
* `wwsympa_url` parameter is set.
* `rfc2369_header_fields` parameter contains `unsubscribe`.
* message personalization is enabled.
* DKIM signing is available (required by the RFC).
One-click link URL will be expired in 7 days to prevent abuse.
This may fix #1210.
> RFC 8058 One-Click Unsubscribe (#1210)

- src/lib/Marc/Search.pm
WWSympa: `msg` (ex. `arcsearch_id`) crashes with the list without archives.
This bug was reported by @mpkut .
> WWSympa: `msg` (ex. `arcsearch_id`) crashes

- default/sympa.wsdl
Define services getDetails, setDetails and setCustom
> Fix incomplete `sympa.wsdl`

- Makefile.am
- src/lib/Sympa/Config/Schema.pm
- src/lib/Sympa/HTMLSanitizer.pm
- t/HTMLSanitizer.t
> Sympa::HTMLSanitizer: Avoid bug in HTML::StripScripts, reDoS with style attribute (#1573)

- default/mail_tt2/report.tt2
- src/lib/Sympa/List.pm
> When owners/moderators are added, "N subscribers added" is shown

- default/mail_tt2/report.tt2
- src/cgi/wwsympa.fcgi.in
> WWSympa: Invalid input on sso_login form floods listmaster notification (#1654)

- src/lib/Sympa/Config/Schema.pm
- src/lib/Sympa/DataSource/LDAP.pm
- src/lib/Sympa/DataSource/LDAP2.pm
Fix for #57
It includes a new configuration setting "page size" that's used both to enable paging, and to define the page size. I tried to integrate a description in the setting, as I think it's good to keep the documentation in/next to the functionality, but I'd suppose that the description/documentation can be improved, feedback really welcome on this.
Now, The code for the LDAP data sources is quite convoluted, difficult to read, etc... It took me a looong time to understand that "two-level" was practically working out of the box once I had implemented "one-level", LOL). I've the feeling that it could be simplified. I've entered a different ticket on this: #1738 , as this is clearly not part of #57 .
> Inclusion from LDAP data sources supports RFC 2696 Paged Results control (#57)

- src/lib/Sympa/Request/Handler/update_automatic_list.pm
> Can't locate object method "new" via package "Sympa::Aliases" (#1710)

- src/cgi/wwsympa.fcgi.in
When using the reject URL sent in the moderation notification mail, there is no message_template argument, creating an error. This commit adds a default value for the argument.
The reject URL is like `https://example.org/sympa/reject/the_list/token_created_by_sympa`.
The error was
```
DIED: Parameter $tpl is not defined at /var/sympa/share/sympa/lib/Sympa/Message/Template.pm line 64.
```
And a stacktrace, leading me to the FCGI script.
> 🐛 — Fix error when rejecting message from direct URL

- src/lib/Sympa/CLI/upgrade.pm
Currently the `sympa upgrade` cli command when not given an explicit previous version via the from parameter checks the file data_structure.version in the config directory. But instead of stopping if this also doesn't exist it assumes the previous version to be zero an consequently tries to apply all data upgrades. This patch just lets upgrade err on the safe side. If the previous behavior is needed passing along a `--from 0` should suffice.
> Upgrade command should fail if no previuos version number can be found.

- src/lib/Sympa/Request/Handler/info.pm
> INFO mail command pulls different owners and/or moderators than those with web UI (#1732)

- src/lib/Sympa/Spindle/ToModeration.pm
DSN reporting a delay with 4.3.0 "forwarded to moderator(s)" may mess the parent of nested list by triggering bounce processing. Failure status should not be used.
This PR may fix #1699 .
> DSN with status 4.3.0 may mess the parent of nested list (#1699)

- service/Makefile.am
- src/libexec/Makefile.am
Version
-------
Maybe any, with GNU make 4.3
Installation method
-------------------
Source.
Expected behavior
-----------------
No warnings during `make` is running.
Actual behavior
---------------
Warnings are shown:
``` code
...
Making all in libexec
make[2]: Entering directory '/.../.../src/libexec'
Makefile:961: warning: ignoring prerequisites on suffix rule definition
...
Making all in service
make[1]: Entering directory '/.../.../service'
Makefile:613: warning: ignoring prerequisites on suffix rule definition
Makefile:597: warning: ignoring prerequisites on suffix rule definition
Makefile:607: warning: ignoring prerequisites on suffix rule definition
...
```
Steps to reproduce
------------------
Extract the source, and then run:
``` bash
$ autoreconf -i
$ ./configure
$ make
``` …
> "warning: ignoring prerequisites on suffix rule definition" with GNU make 4.3

- src/cgi/sympa_soap_server.fcgi.in
- src/lib/Makefile.am
- src/lib/Sympa/CLI/test/soap.pm
- src/lib/Sympa/WWW/SOAP.pm
- src/lib/Sympa/WWW/SOAP/FastCGI.pm
Broken output with SOAP API due to mixture of byte- and utf8-strings.
This may fix #1541.
This also reverts a redundant fix which has been done at 39ddf25 (#1407).
> Broken output with SOAP API due to mixture of byte- and utf8-strings (#1541)

- src/lib/Sympa/CLI/instantiate.pm
- src/sbin/sympa.pl.in
sympa instantiate: Progress bar could not be inactivated by "--quiet" option, though it is documented.
Additionally, "--quiet" should be replaced with "--noout" with new command line format.  See also #1518.
This PR may fix #1567.
> sympa instantiate: Progress bar could not be inactivated

- default/web_tt2/arcsearch_form.tt2
- default/web_tt2/compose_mail.tt2
- default/web_tt2/manage_template.tt2
- default/web_tt2/rss_request.tt2
- default/web_tt2/search_list_request.tt2
- default/web_tt2/serveradmin.tt2
- default/web_tt2/sso_login.tt2
> WWSympa: Screen Reader needs clear labels for text fields (#1748)

- src/lib/Sympa/Message.pm
- src/lib/Sympa/Tools/Text.pm
* Getting {gecos} field from incoming message, display name in `From:` field should be unquoted.
* Setting display name in `From:` field of the message sent by system, the name should be quoted only if necessary.
This PR may fix #999, with the latter in above.
> Display name in `From:` header field should be quoted / unquoted appropriately

- default/web_tt2/head_javascript.tt2
- default/web_tt2/suboptions.tt2
- default/web_tt2/suspend_request.tt2
- default/web_tt2/viewlogs.tt2
- src/cgi/wwsympa.fcgi.in
- src/lib/Sympa/Log.pm
- src/lib/Sympa/Regexps.pm
- www/js/sympa.js
Instead, use browser's built-in widget with <input type="date"> element.
This may fix #1751.
> Use browser's built-in "date" widget instead of jQuery UI Datepicker that is inaccessible using keyboard (#1751)

- default/web_tt2/css.tt2
I asked a friend who worked in web accessibility about [my solution](https://github.com/sympa-community/sympa/issues/1752#issuecomment-1833384255) and he said it was quite the best you can do about this specific problem.
> ♿ — WWSympa: The items in the multiselect box are not readable fully (#1752)

- src/lib/Sympa.pm
> Improve diagnostic messages in the DSNs generated by Sympa

- src/lib/Sympa/Tools/DKIM.pm
> DKIM: i= tag may not match in some auto-generated messages (#1716)

- default/web_tt2/import.tt2
- default/web_tt2/review.tt2
- src/cgi/wwsympa.fcgi.in
For https://github.com/sympa-community/sympa/issues/648
> (AB) add an invite feature to WWSympa

- default/web_tt2/renewpasswd.tt2
- src/cgi/wwsympa.fcgi.in
> Add links to create or recreate password (#1713)

- src/lib/Sympa.pm
- src/lib/Sympa/Message/Template.pm
> The length of boundary lines in multipart messages could exceed 70 octets (#1795)

- src/lib/Sympa/Spindle/TransformIncoming.pm
- t/Spindle_TransformIncoming.t
This may fix #1811 .
This PR depends on #1668.
> Allow "custom_subject" to be at the beginning of the subject (#1811)

- src/lib/Sympa/DataSource/List.pm
If the Sympa::List->new($name, $robot, $options) constructor is called with an optional $robot parameter specified, then that $robot overrides any domain that may be present in $name.  When constructing a DataSource for inclusion, the robot of the DataSource should be inferred only if no domain is present in the list name.
> Fix cross-robot list inclusion (#1797)

- default/web_tt2/modindex.tt2
The moderation help said "To read a message, click on its subject", but it wasn’t true, you needed to click on the eye icon. The eye icon it quite counter-intuitive, people has the reflex to click on the subject of the mail to see it, like on mail clients.
It sounded better to me to make the interface like the documentation instead of modifying the documentation.
> 🐛 — [moderation] Show message content when clicking on its object

- src/cgi/wwsympa.fcgi.in
One line patch to stop "No command found in message" emails to sympa-request  when multiple list moderators try to approve the same message.
> Stop "do_distribute" actions from Web interface from generating backscatter emails to sympa-request alias (#1737)

- src/lib/Conf.pm
- src/lib/Sympa/Aliases.pm
- src/lib/Sympa/List.pm
- src/lib/Sympa/Scenario.pm
> Noise in Apache error_log (again) (#1325)

- src/lib/Sympa/CLI.pm
For example,
```
sympa config dmarc_protection.mode="dmarc_reject" 
```
was rejected due to `Invalid argument 'dmarc_protection.mode=dmarc_reject' ("key=value" is expected)`.
This PR may fix it.
> CLI: With `sympa config key=value`, key couldn't contain dot

- src/lib/Sympa/CLI/help.pm
Some distributions (Debian and its descendants) separate `perldoc` from the package for Perl and replace it with a stub.  Use `perldoc` only if such stub wouldn't be used.  See [Debian Bug\#1062398](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1062398) for details.
This PR fixes this problem.  However, package maintainers are encouraged to activate `perldoc` for better user experiences.
> Debian Bug#1062398 Lacks dependency on `perldoc` utility

- src/lib/Sympa/Config/Schema.pm
- src/lib/Sympa/Regexps.pm
- src/lib/Sympa/Spindle/TransformOutgoing.pm
The `custom_header` should not contain non-ASCII characters.
Additionally, some minor bugs are fixed.
This may fix #1840.
> Prevent custom_header with non-ASCII characters (#1840)

- doc/auth.conf.pod
- src/cgi/wwsympa.fcgi.in
- src/lib/Conf.pm
- src/lib/Sympa/CLI/test/ldap.pm
- src/lib/Sympa/Config/Schema.pm
- src/lib/Sympa/DataSource/LDAP.pm
- src/lib/Sympa/ListOpt.pm
- src/lib/Sympa/Scenario.pm
- src/lib/Sympa/WWW/Auth.pm
> LDAP: Add `deref` option to specify how to dereference aliases

- src/cgi/wwsympa.fcgi.in
Version
-------
6.2.37b and later.
Installation method
-------------------
Any.
Expected behavior
-----------------
When `distribute` action is initiated by requesting URI `wwsympa_url/LIST/distribute/ID`, confirmation steps should always be performed.
Actual behavior
---------------
The confirmation steps are skipped, when message tagging is optional or no message tags are available on the list.
Steps to reproduce
------------------
Post a message to the list that requires holding messages for moderation.  And follow the `distribute` link for the held message.
Note
----
For `reject` action see #1704 also.
> WWSynmpa: do_distribute: Confirmation was not always performed

- src/lib/Sympa/Internals/Workflow.pod
- src/lib/Sympa/Message.pm
- src/lib/Sympa/Spindle/AuthorizeMessage.pm
- src/lib/Sympa/Spindle/DoForward.pm
- src/lib/Sympa/Spindle/ProcessModeration.pm
- src/lib/Sympa/Spindle/ProcessOutgoing.pm
- src/lib/Sympa/Tools/Data.pm
- src/lib/Sympa/Tracking.pm
This PR includes following fixes:
* Correct order of ARC seal and DKIM signature.
* The messages for domain/list admins also should have DKIM signature.
* The messages for domain/list admins now are queued in outgoing spool as a result of refactoring.
This may fix #1851 .
This also requires #1717 .
> Several fixes/improvements on ARC seal & DKIM signature

- src/lib/Sympa/Config/Schema.pm
- src/lib/Sympa/Message.pm
- src/lib/Sympa/Spindle/ProcessOutgoing.pm
This may fix #1852.
This depends on #1869 .
> DKIM-Signature header fields should not be removed even if invalid (#1852)

- src/lib/Sympa/Request/Handler/include.pm
> Bad inclusion label subscriber with long path (#1943)

- src/lib/Sympa/Message.pm
The issue arises when sending from a multi-word sender (something with spaces in it) that is not MIME encoded. MIME::EncWords does nothing in this case.
> Fix dmarc_protection from address
