src/lib/Sympa/Database.pm

Add DBI error string to error message "Can't connect to Database"

---

src/lib/Sympa/List.pm

Issue #40: Warning on uninitialized value during delivery to the list

---

src/lib/Sympa/ConfDef.pm
src/lib/Sympa/HTMLSanitizer.pm

Additional bug fixes and enhancements for PR #45

---

default/web_tt2/pref.tt2
src/lib/Sympa/Request.pm
src/lib/Sympa/Spindle/AuthorizeRequest.pm

Fix for Issue #25 was broken.
- Typo in template.
- Authorizing move_user function causes crash.

Issue #25: move_user function was broken

---

src/lib/Sympa/List.pm

More fix to PR #66: Use do_prepared_query().

More fix to PR #66

---

default/web_tt2/edit_attributes.tt2

Fix fo issue #61: Entirely replaced edit_attributes.tt2 so that table won't be used.

Fix fo issue #61

---

src/lib/Sympa/List.pm

Allow multiple attrs in include_ldap_2level_query

---

.travis.yml
src/cgi/wwsympa.fcgi.in
src/lib/Sympa/ConfDef.pm
src/lib/Sympa/ModDef.pm
src/lib/Sympa/Upgrade.pm

For issue #69:
- [change] WWSympa: Now FastCGI is mandatory: CGI support has been dropped.

Issue #69: Make FastCGI support mandatory

---

src/cgi/wwsympa.fcgi.in
src/lib/Sympa/Log.pm

Log list not sorted for date #70

---

default/web_tt2/review.tt2

Review.tt2 button correction. #98

---

default/mail_tt2/listmaster_notification.tt2

Old style names in the notification template.

Old variable names used in listmaster error mail

---

default/web_tt2/confirm_action.tt2
src/cgi/wwsympa.fcgi.in

Issue #76: Change Redirect After List Admin Updates a User's Email

---

src/cgi/wwsympa.fcgi.in

Fxies issue #93

---

src/lib/Sympa/List.pm
src/lib/Sympa/Spindle/ResendArchive.pm
src/lib/Sympa/Spindle/TransformOutgoing.pm

Fixes: Archived-At: field on resent archived message is wrong. #111

Fixes issue #111

---

src/lib/Sympa/Robot.pm

Fixes issue #91.  Now topic identfiers (names) in topics.conf will be normalized to lowercase.

Topic names in topics.conf with uppercase are ignored #91

---

default/mail_tt2/listmaster_notification.tt2

PR #121 with some modification.

Fix listname typo #121, revised

---

src/lib/Sympa/List.pm
src/lib/Sympa/Upgrade.pm

Before rebuilding admin_table, won't clear it #71

---

src/lib/Sympa/DatabaseDriver/LDAP.pm

Cosmetic issue in error message with ldap driver #132

---

www/Makefile.am
www/external/jquery-migrate.js

Issue #78 quickfix

---

Makefile.am
www/Makefile.am

Create css_path during installation #148

---

default/web_tt2/modindex.tt2

[enhancement] change modindex.tt2 to improve mass moderation

---

default/web_tt2/css.tt2
default/web_tt2/modindex.tt2

Additional modification to fix issue #122.

Additional modification to PR#141 by l4uc3 (issue #122)

---

src/lib/Sympa/List.pm

Fixes #166 Synchronize members with data source and task manager crash randomly.
Made complicated code be simpler.

Issue #166

---

default/mail_tt2/report.tt2
src/cgi/wwsympa.fcgi.in

Show a bit more detailed log failing to parse HTML message.
See issue #44.

Issue #44 fix 2

---

src/lib/Sympa/Upgrade.pm

Issue #43: Preliminary notice on abolishment of "host" list parameter.

---

Makefile.am

As in title, not much else to say :-)
Regards,
Xavier

Use standard 644 perms for $sysconfdir/README

---

src/cgi/wwsympa.fcgi.in

Issue #212: Notification not sent to the owner when a list is confirmed by a listmaster

---

src/cgi/wwsympa.fcgi.in
src/lib/Sympa/DatabaseDescription.pm
src/lib/Sympa/List.pm

A tentative fix for issue #11.
Since radical fix (I'm working on [here](https://github.com/ikedas/sympa/commits/issue-11_try3)) will take time, we would be better to apply changes restraining erroneous behavior.

Tentative fix for issue #11

---

default/web_tt2/suboptions.tt2
src/cgi/wwsympa.fcgi.in
src/lib/Sympa/List.pm
src/lib/Sympa/Template.pm

WWSympa: Dates in "subscriber option" page are shown in epoch format

---

src/lib/Sympa/WWW/SOAP.pm

SympaSOAP crashes with add, closeList and del #244

---

src/lib/Conf.pm
src/lib/Sympa/ConfDef.pm

cookie parameter protection #243

---

default/web_tt2/head_javascript.tt2
default/web_tt2/head_ui.tt2
www/Makefile.am

This PR includes one patch that fixes several regression I introduced in www/Makefile.am while rebasing.
Also, I noticed several jquery-ui images stored in the repository are not shipped in the tarball, this is the second patch.
I added a third patch to fix location of foundation.js, missed when moving it one level up.

foundation6: www/Makefile.am fixes 

---

src/cgi/wwsympa.fcgi.in

GH #341: "filter" parameter for "search" action was omitted.

---

.travis.yml
Makefile.am
cpanfile
doc/dot.perltidyrc
xt/perltidy.t

Merge create-cpanfile to sympa-6.2

---

default/web_tt2/config_common.tt2
default/web_tt2/edit.tt2
default/web_tt2/edit_attributes.tt2
default/web_tt2/edit_list_request.tt2
default/web_tt2/review.tt2
default/web_tt2/suboptions.tt2
default/web_tt2/suspend_request.tt2
www/js/sympa.js

This is not a bug but includes small refactorings missed by PR #348.

Refactor config pages (not a bug)

---

cpanfile
src/sbin/sympa_wizard.pl.in

Adding minimum version of Perl to cpanfile.

---

src/lib/Sympa/Request/Handler/close_list.pm

close_list may crash with typos.

---

src/lib/Sympa/Request/Handler/move_list.pm

Lost owners/moderators by "Copy list" action

---

src/sbin/sympa.pl.in

This PR may fix issue #62.
See also issue #382.

sympa.pl: Add an option "--open_list=list@domain" to restore closed list

---

src/lib/Sympa/Bulk.pm
src/lib/Sympa/Request/Handler/move_list.pm
src/lib/Sympa/Request/Message.pm
src/lib/Sympa/Spool.pm
src/lib/Sympa/Spool/Auth.pm
src/lib/Sympa/Spool/Digest.pm
src/lib/Sympa/Spool/Held.pm

This may fix issue #368.
This PR depends on PR #377.

Rename a list takes incredible time #368

---

src/lib/Sympa/List/Users.pm
src/lib/Sympa/ListDef.pm

Prevent the use of the list address as owner or moderator #297

---

default/mail_tt2/report.tt2
src/lib/Sympa/Request/Handler/move_user.pm

sympa.pl --change_user_email no longer working with 6.2.34 #389

---

www/js/sympa.js

Add copyright notice to sympa.js #320

---

src/lib/Sympa/Spindle/ProcessBounce.pm

These are changes to ProcessBounce.pm that where previously attached to issue #448. Handling of bounce messages from latest versions of Exim.

Exim's new bounce text handling, issue #448

---

xt/perltidy.t

This may be an enhancement to PR #322.
See also #440 for detail.

Test: Make xt/perltidy.t to check *.pl.in and *.fcgi.in as well.

---

src/lib/Sympa/List/Users.pm

Sympa 6.2.36: Crash of web interface when editing list moderators #456

---

src/lib/Sympa/Request/Handler/move_list.pm

- [bug] Moving/copying a list, existing list may be overwritten (if list_check_smtp feature is not available).
* Note: Owners and moderators of source list would be also copied so that owners of source list could get privileges on target list.
Fixed by checking if target list already exists.

Moving/copying a list, existing list may be overwritten

---

src/lib/Sympa/Aliases.pm
src/lib/Sympa/Request/Handler/move_list.pm

Crash in create_list_request when list name is missing #490

---

src/lib/Sympa/Message.pm

Add a etc/mail_tt2/message.global_footer or etc/mail_tt2/message.global_footer.mime file and it will be added to all messages.
Obviously, only admins can edit that file.
It can be used to add an unsubscribe link while letting users add their own list signature.
Will fix #301

Fix #301 — Add global mail signature feature

---

default/web_tt2/confirm_action.tt2
default/web_tt2/import.tt2
default/web_tt2/review.tt2
src/cgi/wwsympa.fcgi.in
src/lib/Sympa/ConfDef.pm
src/lib/Sympa/Request/Handler/add.pm
src/lib/Sympa/Request/Handler/subscribe.pm

Add a global quiet_subscription setting which enforce the "quiet add" policy

---

src/lib/Conf.pm

[bug] Primary `auth.conf`, `crawlers_detection.conf` and `trusted_applications.conf` won't be used by non-primary domains by default.
Fixed by using appropriate function to search paths of config files.
This PR may fix #432.

Primary `auth.conf` etc. won't be used by non-primary domains

---

default/mail_tt2/listowner_notification.tt2
default/web_tt2/confirm_action.tt2
po/sympa/ca.po
po/sympa/de.po
po/sympa/el.po
po/sympa/en_US.po
po/sympa/es.po
po/sympa/et.po
po/sympa/eu.po
po/sympa/fi.po
po/sympa/fr.po
po/sympa/gl.po
po/sympa/hu.po
po/sympa/it.po
po/sympa/ja.po
po/sympa/ko.po
po/sympa/nb.po
po/sympa/nl.po
po/sympa/oc.po
po/sympa/pl.po
po/sympa/pt_BR.po
po/sympa/ro.po
po/sympa/ru.po
po/sympa/sv.po
po/sympa/vi.po
po/sympa/zh_CN.po
po/sympa/zh_TW.po
src/cgi/wwsympa.fcgi.in

Issue with the message sent to owners to allow unsubscribing #469

---

support/README.support.md
support/pod2md

Maintenance support scripts (2)

---

src/lib/Sympa/Upgrade.pm

Upgrading from 6.1.11 or earlier, `exclusion_table` might not be updated properly.
Fixed by updating the table ---
1. not according to list membership of user in user_exclusion field.
Currently the lists in which the user is not subscribing are skipped.
2. removing the rows with the name of list which does no longer exist.
Currently Sympa reports that _zero_ candidates for robot are there.
See also #546.

exclusion_table might not be updated properly during "sympa.pl --upgrade"

---

default/mail_tt2/message_report.tt2
default/mail_tt2/user_notification.tt2
src/cgi/wwsympa.fcgi.in
src/lib/Sympa/List.pm
src/lib/Sympa/Template.pm

Additional removal of code to kill VOOT support.

---

default/web_tt2/import.tt2
www/js/sympa.js

import.tt2: non-working line break in toolip (#562)

---

src/cgi/wwsympa.fcgi.in

Reset WWSympa's session when SSO session refreshed (#560)

---

src/cgi/wwsympa.fcgi.in
src/lib/Sympa/ListDef.pm
src/lib/Sympa/Regexps.pm
src/lib/Sympa/Scenario.pm

Additional changes to: Salaun urennes1/fix scenario name with dots (#589)

---

default/web_tt2/editfile.tt2

Fix #622
Thx to dpc22 who created the issue AND gave the solution

Fix message_header and message_footer links not showing in editfile page

---

src/cgi/wwsympa.fcgi.in
src/lib/Sympa/User.pm

Updating user crashes due to missing serialization of structured data. (#641)

---

src/lib/Sympa/User.pm

Additional fix to PR #659 by racke.  This i8s one of fixes for #656.

Spurious warnings for uninitialized values.

---

.travis.yml
cpanfile
t/compile_executables.t
t/compile_modules.t

Tests with Test::Compile crash.
This PR will be merged immediately.

Support Test::Compile 2.0.0

---

default/web_tt2/subindex.tt2

Fix error in subindex.tt2, subscribtions reject button does not work

---

default/mhonarc-ressources.tt2
default/web_tt2/confirm_action.tt2
src/cgi/wwsympa.fcgi.in
src/lib/Sympa/Spindle/ProcessArchive.pm

Add « report as spam » option when deleting archives

---

src/lib/Sympa/Message.pm

DMARC protection: "p" tag is not applied to subdomains #654

---

src/lib/Sympa/List.pm

Additional fix to #516

---

src/lib/Sympa/List.pm

Fix tidying of src/lib/Sympa/List.pm

---

default/web_tt2/info.tt2

web_tt2/info.tt2 generates some noise in stderr

---

src/lib/Sympa/Tools/File.pm

stats page generates spurious warnings in stderr (#700)

---

src/lib/Sympa/List.pm
src/lib/Sympa/Request/Handler/include.pm

More fix to #516 (deadly typos).

More fix to #516

---

cpanfile

Update Text::LineFold (#709)

---

src/cgi/wwsympa.fcgi.in

This may solve #716 partially.

WWSympa: send_mail: Restrict MIME content type of uploaded HTML text (#716)

---

src/cgi/wwsympa.fcgi.in

"Requested date" of renamed list with "pending" status is inappropriate (#720)

---

default/web_tt2/editsubscriber.tt2
default/web_tt2/list_panel.tt2
default/web_tt2/my.tt2
default/web_tt2/viewlogs.tt2
src/cgi/wwsympa.fcgi.in
src/lib/Sympa/ListOpt.pm
src/lib/Sympa/Template.pm

Pending lists not clearly shown as "pending" in the web GUI (#738)

---

src/sbin/sympa.pl.in

Verify robot names passed to --make_alias_file command line option

---

src/cgi/wwsympa.fcgi.in
src/lib/Sympa/DataSource/File.pm
src/lib/Sympa/DataSource/RemoteFile.pm
src/lib/Sympa/DataSource/SQL.pm

Fixes bugs found after #693.
This may fix #761.
This may fix #762. 
This may fix #763. 
This may fix #766.

Fixes related to #693

---

src/lib/Sympa/Archive.pm
src/lib/Sympa/Spindle/ProcessArchive.pm

Archive directories of any lists may be created even if archive is unavailable, or Sympa may crash (#736)

---

src/cgi/wwsympa.fcgi.in

WWSympa: compose_mail: "Date:" field was omitted. Add it. (#791)

---

default/scenari/create_list.listmaster
default/scenari/create_list.public_listmaster
default/scenari/del.owner
doc/samples/intranet/scenari/create_list.intranet
doc/samples/intranet/scenari/subscribe.intranetorowner
doc/samples/intranet/scenari/visibility.intranet

Additional fixes for #775: Missing `dkim` in scenarios.

---

src/lib/Sympa/Message.pm

DMARC protection: Bug injected on 6.2.48: Could not parse DMARC records.
This may fix #783 .

Fixing #783

---

Makefile.am
src/cgi/wwsympa.fcgi.in
src/lib/Sympa/Config_XML.pm
src/lib/Sympa/Request/Handler/create_list.pm
src/lib/Sympa/WWW/SOAP.pm
src/sbin/sympa.pl.in
t/Config_XML.t

Family: Fixing bugs injected by #771 (#815)

---

src/lib/Sympa/Spindle/ProcessIncoming.pm

Fixes #820

---

src/lib/Sympa/Tools/Text.pm

Fixing a bug injected by 83f6907 (6.2.45b.3). (#822)

---

.travis.yml

This pr will be committed immediately.

Rearrange .travis.yml

---

t/Tools_Text.t

Addition to #829

---

doc/sympa_scenario.pod
src/lib/Sympa/Scenario.pm

Check for some variables were too restrictive. And some small fixes.
This may fix #841.

Addition to fixes for #831 (#833)

---

src/lib/Sympa/Scenario.pm

This may fix #844 .
This may fix #845 .

Additional fixes to #841.

---

src/cgi/wwsympa.fcgi.in

Bug: Crash by assigning to uninitialized hashref (#846)

---

src/lib/Sympa/Scenario.pm

Additional fix for #841

---

.gitlab-ci.yml
.travis.yml
Makefile.am

Adding some missing things to PR #840.
This PR is mostly cosmetic and will be committed soon.

Addition to #840

---

.gitlab-ci.yml
.travis.yml
Makefile.am
t/Message_smime.t

Some cases are missing and wait for addition in the future.
Updates #868.
This PR will be merged immediately.

Adding tests for #868

---

src/lib/Sympa/DataSource/File.pm

Reported by Amos on [sympa-users](https://listes.renater.fr/sympa/arcsearch_id/sympa-users/2020-02/CAK2viQXc73pKWT6usqRAyB3gZQD9d7qqLkuBbz%3D0UQWL9JpM0Q%40mail.gmail.com).

Data source: File: gecos was ignored

---

src/cgi/wwsympa.fcgi.in

WWSympa: Bug: Accessing to /sympa/help may crash

---

src/cgi/wwsympa.fcgi.in

This is a fix for SA-2020-001 (#886) .

[SA 2020-001] Security flaws in CSRF prevension (#886)

---

src/lib/Sympa/Message.pm

Recommended file name won't be decoded with earlier version of MIME-tools.
This may fix #889 .

urlize: File names in URLized parts are incorrect (#889)

---

t/Tools_Text.t

t/Tools_Text.t fails without optional modules (#892)

---

Makefile.am
src/lib/Sympa/Scenario.pm
t/Scenario.t

Scenario: Prevent crashing by fatal error in syntax of regexp (#860)

---

src/lib/Sympa/DataSource/RemoteDump.pm
src/lib/Sympa/DataSource/RemoteFile.pm

Data sources: RemoteFile and RemoteDump: Log subject, issuer and cipher of peer.

Data sources: remote file/remote list: Log description of certificate of the peer

---

default/mail_tt2/report.tt2
src/lib/Sympa/Request/Handler/include.pm

`sympa.pl --sync_include`: No errors weren't reported to caller, even if one or more of data sources failed inclusion.
This PR depends on PR #905 .
This PR may fix #907 .

`sympa.pl --sync_include`: No errors were reported to caller

---

default/web_tt2/login_menu.tt2
src/cgi/wwsympa.fcgi.in

After login, the last content, not always the last page, is shown (#580)

---

src/cgi/wwsympa.fcgi.in

list index performance update for wwsympa.fcgi do_lists subroutine (#925)

---

src/lib/Sympa/DatabaseDriver/MySQL.pm
src/lib/Sympa/DatabaseDriver/PostgreSQL.pm
src/lib/Sympa/DatabaseDriver/SQLite.pm

This PR will be merged immediately.

Typos in set_index() of some DatabaseDriver classes.

---

src/lib/Sympa/Config_XML.pm
t/Config_XML.t

"false" values in XML file prevent list creation (#953)

---

src/lib/Sympa/Message.pm

Uunexpected error log "Unable to verify S/MIME signature" (#963)

---

src/cgi/wwsympa.fcgi.in

Sympa CAS logout_path does not work (#986)

---

src/lib/Sympa/List.pm

There is no save method in Sympa::List anymore.

Updating Sympa::List's POD

---

src/lib/Sympa/List.pm

Oracle: ORA-00904: "EMAIL": invalid identifier (#1013)

---

src/sbin/sympa_newaliases.pl.in

sympa_newaliases.pl: Removing ineffective command line options

---

src/lib/Sympa/List.pm

This may fix #1016.
This may fix #969, in combination with #973 & #997 .

Additional fix to #973 & #997 (#969)

---

configure.ac
src/cgi/Makefile.am
src/libexec/Makefile.am

configure: Add options --disable-setuid_newaliases and --disable-setuid
This may fix #1031

Add option to ./configure which prevents installation of sympa_newaliases-wrapper (#1031)

---

default/edit_list.conf
default/web_tt2/compose_mail.tt2
src/bin/upgrade_bulk_spool.pl.in
src/cgi/wwsympa.fcgi.in
src/lib/Conf.pm
src/lib/Sympa/Config/Schema.pm
src/lib/Sympa/ListOpt.pm
src/lib/Sympa/Message.pm
src/lib/Sympa/Spindle/AuthorizeMessage.pm
src/lib/Sympa/Spindle/ProcessOutgoing.pm
src/lib/Sympa/Spindle/ToList.pm

Limit personalization:
- Only when posted from WWSympa, entire text will be converted. Otherwise only footer/header will be converted.
This may fix #1037 .

Limited personalization

---

src/cgi/wwsympa.fcgi.in

Missing language on edit subscriber view (#1048)

---

src/lib/Sympa/Message.pm
src/lib/Sympa/Message/Template.pm
src/lib/Sympa/Spindle/ProcessOutgoing.pm
src/lib/Sympa/Tools/DKIM.pm

DKIM signing not working if dkim_feature in domain context was not enabled (#1036)

---

src/lib/Sympa/Config/Schema.pm
src/lib/Sympa/Message.pm
src/lib/Sympa/Message/Template.pm
src/lib/Sympa/Spindle/ProcessOutgoing.pm
src/lib/Sympa/Tools/DKIM.pm

This may really fix #1036 (See the comment in that issue page).

Correct fix for #1036

---

src/cgi/wwsympa.fcgi.in

This may fix (part of) #1066 .

Fix regression in personalization feature (#1066): Case 2bis

---

doc/sympa_config.podpl

- Adding sections "Renamed parameters" and "Deprecated parameters".
- Adding reference to "Directory layout" page.
- Some corrections.

Updating sympa_config(5)

---

src/lib/Sympa/Config/Schema.pm

Improve labels for web_apply_on and mail_apply_on

---

default/web_tt2/confirm_action.tt2
default/web_tt2/renewpasswd.tt2
src/cgi/wwsympa.fcgi.in

Add confirmation to requestpasswd action to prevent spamming

---

src/lib/Sympa/Aliases.pm
src/sbin/sympa.pl.in

Fix and speed up make_alias_file Sympa command (#1046)

---

src/lib/Sympa/Spindle/AuthorizeMessage.pm

Fixing #1063

---

src/lib/Conf.pm

Remove undocumented backtick syntax in sympa.conf

---

src/lib/Sympa/List.pm
src/lib/Sympa/Tools/Text.pm

Addition to #1053: Clip subject safely

---

src/cgi/wwsympa.fcgi.in

Default config breaks web GUI post (#1104)

---

src/lib/Sympa/List.pm

This is a candidate of fixes for #1090.

`edit_list.conf` may be reloaded only when it has to (#1090)

---

default/Makefile.am
default/mail_tt2/report.tt2
default/web_tt2/admin.tt2
default/web_tt2/blocklist.tt2
default/web_tt2/css.tt2
default/web_tt2/modindex.tt2
default/web_tt2/nav.tt2
default/web_tt2/review.tt2
default/web_tt2/viewmod.tt2
src/cgi/wwsympa.fcgi.in
src/lib/Conf.pm
src/lib/Sympa/Config/Schema.pm
src/lib/Sympa/List.pm
src/lib/Sympa/Log.pm
src/lib/Sympa/Request/Handler/add.pm
src/lib/Sympa/Request/Handler/subscribe.pm
src/lib/Sympa/Scenario.pm
src/lib/Sympa/Tools/Domains.pm
src/lib/Sympa/Upgrade.pm
src/sbin/sympa_wizard.pl.in
t/data/sympa.conf

Replace "blacklist" with "blocklist" (#1111)

---

src/lib/Sympa/Message.pm

X-Original-DMARC-Record header field may break message (#1113)

---

src/cgi/wwsympa.fcgi.in
src/lib/Sympa/Message.pm
src/lib/Sympa/Spindle/ToList.pm

Refactoring (#1070)

---

src/lib/Sympa/Upgrade.pm

Upgrading fails due to typos (#1144)

---

NEWS.md

Let's start writing the release documentation early.

Release 6.2.62

---

src/lib/Sympa/WWW/Auth.pm

Sympa should not lock out users using password authentication with LDAP (#1132)

---

default/scenari/visibility.identified

This scenario was created for one of my customers and is IMHO a sensible addition, especially in a corporate environment.

Add list visibility scenario for logged in users.

---

src/lib/Sympa/DatabaseDriver/PostgreSQL.pm
src/lib/Sympa/DatabaseDriver/SQLite.pm
src/lib/Sympa/Robot.pm

Error emails to listmaster from repeated set_netidtoemail_db calls (#1163)

---

src/lib/Sympa/Message.pm

Bulk.pl didn't deliver mails if failed to personalize (#1174)

---

NEWS.md

Let's write the release documentation early.

Release 6.2.64

---

src/lib/Sympa/Config.pm
src/lib/Sympa/Spindle/AuthorizeRequest.pm
src/lib/Sympa/WWW/SOAP.pm

Fix noise in HTTP server error log (#1185)

---

src/lib/Sympa/List.pm

delete_list_member() failed removing subscribers' pictures

---

default/mail_tt2/report.tt2
default/scenari/create_list.closed

Add create_list.closed scenario.

---

cpanfile
src/lib/Sympa/Tools/SMIME.pm

S/MIME: subjectAltName in certificate couldn't be parsed properly (#1196)

---

src/lib/Sympa/Config/Schema.pm

Also add site default for distribution_ttl

Make distribution_ttl and inclusion_notification_feature site-wide

---

src/lib/Sympa/Message.pm

Some more changes to ldidry/1174 followup

---

src/lib/Conf.pm

This has been injected on commit 5b5fd55 and affects 6.2.57b.1 to 6.2.64.

custom_robot_parameter parameter was broken

---

default/web_tt2/head_javascript.tt2
www/js/jquery.js

WWSympa: Update jQuery to 3.6.0 (#1204)

---

cpanfile

Drop a dependency Socket6 (#1211)

---

src/lib/Sympa/Request/Handler/subscribe.pm

The "subscribe" requests ignored custom_attribute (#1199)

---

src/lib/Sympa/List.pm

edit_list.conf was loaded multiple times and wasted memory.
~This may fix #1170.~

edit_list.conf should not be loaded multiple times to waste memory

---

default/web_tt2/css.tt2

WWSympa: Misleading line folding in the tooltip (#1262)

---

src/bin/arc2webarc.pl.in
src/bin/tpl2tt2.pl.in
src/bin/upgrade_sympa_password.pl.in
src/cgi/wwsympa.fcgi.in
src/lib/Conf.pm
src/lib/Sympa/Family.pm
src/lib/Sympa/List.pm
src/lib/Sympa/Message.pm
src/lib/Sympa/Message/Template.pm
src/lib/Sympa/Process.pm
src/lib/Sympa/Request/Handler/create_automatic_list.pm
src/lib/Sympa/Request/Handler/move_list.pm
src/lib/Sympa/Request/Handler/update_automatic_list.pm
src/lib/Sympa/Spindle/ProcessTask.pm
src/lib/Sympa/Tools/SMIME.pm
src/lib/Sympa/Upgrade.pm
src/lib/Sympa/WWW/Tools.pm
src/libexec/ldap_alias_manager.pl.in
src/sbin/sympa.pl.in
src/sbin/sympa_wizard.pl.in

Cleanup: Avoid using bareword filehandles. And some copyedits.

Cleanup: Avoid using bareword filehandles etc.

---

src/cgi/wwsympa.fcgi.in
src/lib/Sympa/Request/Handler/add.pm
src/lib/Sympa/Request/Handler/del.pm
src/sbin/sympa.pl.in
t/Request_Handler_add+del.t

- Remove redundant calls of Sympa::List::is_subscription_allowed().
More fixes to #1251

More refactoring for PR#1251

---

default/web_tt2/serveradmin.tt2

This PR was created to correct the cosmetic problems detailed in issue #1294

Cosmetic problems in Listmaster Admin menu

---

default/web_tt2/css.tt2

* &lt;em&gt; element was not rendered as emphasized.
* Inproper font size in footer and lists.
* Preset fonts are hard to read comfortably (#1305).
This may fix #1305.

Stylesheet: Fixing minor bugs in css.tt2

---

.gitignore

Compilation creates some new files that we need to ignore

🙈 — Update .gitignore

---

support/xgettext.pl

- Bug: Couldn't handle escaped quotes.
- Update comments in generated `pot` files.

Improve xgettext.pl

---

.github/workflows/make-check.yml
t/Request_Handler_add+del.t

Test: `add` request omits `quiet` option

---

default/mail_tt2/helpfile.tt2
default/web_tt2/footer.tt2
default/web_tt2/sympa_menu.tt2
doc/samples/robot.conf
doc/samples/sampleClient.php
doc/sympa_toc.pod
src/cgi/wwsympa.fcgi.in
src/libexec/alias_manager.pl.in
src/sbin/archived.pl.in
src/sbin/bounced.pl.in

Migration to the new domain (1): Remove www.sympa.org from the code.

Migration to the new domain (1)

---

src/lib/Sympa/Spindle/TransformIncoming.pm

Typo in PR#1307

---

default/web_tt2/pref.tt2

+ change h4 tags to h3, since it doesn’t semantically make sense

🚸 — Add anchors to prefs to ease linking (like in FAQ, etc.)

---

default/web_tt2/arcsearch.tt2
src/cgi/wwsympa.fcgi.in

Protect email addresses in archive search (#1312)

---

src/lib/Sympa/CLI/rebuildarc.pm

This PR fixes the bug injected by #1286.
- bug reported on [a thread in sympa-users list](https://listes.renater.fr/sympa/arcsearch_id/sympa-users/2022-04/BN7PR08MB49614786362D49A9B06BF2F3DFEA9%40BN7PR08MB4961.namprd08.prod.outlook.com).

Bugs injected by PR#1286 (2)

---

src/lib/Sympa/List.pm

When closed list is restored, subscribers won't be restored (#1380)

---

src/lib/Sympa/Scenario.pm

blocklist sensitive to spurious whitespace (#1377)

---

src/lib/Sympa/Config/Schema.pm

More fixes for #1329

---

src/lib/Sympa/Config/Schema.pm
sympa.conf.in

Remove static_content_url from minimal set.
Additional fixes to #1370

Addition to #1370

---

src/lib/Sympa/WWW/SOAP.pm

Unable to set custom attribute using the SOAP API (if none already set) (#1401)

---

src/libexec/bouncequeue.c
src/libexec/familyqueue.c
src/libexec/queue.c

This may fix #1410, and makes some cosmetic changes.

File names in incoming spool can be truncated (#1410)

---

cpanfile

Missing dependency Pod::Usage

---

src/lib/Sympa/List.pm

This fixes a bug injected by PR #1379.
This may fix #1329.

Additional fix to #1379 (#1329)

---

cpanfile
default/mail_tt2/summary.tt2
default/mhonarc_rc.tt2
default/web_tt2/confirm_action.tt2
default/web_tt2/head_javascript.tt2
default/web_tt2/latest_arc.tt2
default/web_tt2/rss.tt2
default/web_tt2/tracking.tt2
src/cgi/wwsympa.fcgi.in
src/lib/Sympa/List.pm
src/lib/Sympa/Spindle/ProcessDigest.pm
src/lib/Sympa/Template.pm
src/lib/Sympa/Tools/Text.pm
src/lib/Sympa/WWW/Marc/Search.pm
www/js/sympa.js

Note: Rebuilding archives is needed to activate this feature in the past archives.
This may fix #1441.

Web archive: Copy permalink of the message to clipboard.

---

default/web_tt2/review.tt2
default/web_tt2/reviewbouncing.tt2

On review or reviewbounceing page, despite "Page size" selectbox was changed, page size is not changed.

WWSyjmpa: Page size cannot be changed on review and reviewbouncing

---

src/cgi/wwsympa.fcgi.in
src/lib/Sympa/WWW/Tools.pm

Import updates of SMTP status codes from registry:
https://www.iana.org/assignments/smtp-enhanced-status-codes

Update SMTP status codes

---

src/lib/Sympa/Request/Handler/create_automatic_list.pm

Template error parsing not detected (#1474)

---

src/lib/Sympa/Config/Schema.pm
src/lib/Sympa/Message.pm

dmarc_protection.phrase "From" format INCORRECT (#1498)

---

src/lib/Sympa/Message.pm

Exim: Failed to get envelope sender in "Return-path:" field (#1354)

---

default/sympa.wsdl
src/lib/Sympa/WWW/SOAP.pm

Extend info soap function

---

default/mail_tt2/listowner_notification.tt2
default/web_tt2/compose_mail.tt2
default/web_tt2/confirm_action.tt2
default/web_tt2/edit_attributes.tt2
default/web_tt2/subindex.tt2
default/web_tt2/subscriber_table.tt2
src/cgi/wwsympa.fcgi.in
src/lib/Sympa/DataSource/SQL.pm
src/lib/Sympa/List.pm
src/lib/Sympa/Request/Handler/add.pm
src/lib/Sympa/Request/Handler/include.pm
src/lib/Sympa/Request/Handler/subscribe.pm
src/lib/Sympa/Tools/Data.pm
src/lib/Sympa/WWW/SOAP.pm

This may fix #1535.
On this occation, improve the unnecessarily complicated data structure of custom attributes.

Fix and improve custom attribute (#1535)

---

src/lib/Sympa/Tools/DKIM.pm

* When `dkim_parameters.signer_domain` and/or `arc_parameters.signer_domain` did not set, the mail domain name was _not_ used as default.
* With Mail-DKIM 0.58 or earlier DKIM signature / ARC seals were not enabled.

Some bugs with DKIM / ARC

---

src/lib/Sympa/User.pm

Spurious error log adding subscriber (#1532)

---

src/lib/Sympa/CLI/test/soap.pm

"sympa test soap" crashes due to undefined subroutine

---

default/web_tt2/nav.tt2
default/web_tt2/serveradmin.tt2
src/cgi/wwsympa.fcgi.in

Deprecate "System log" setting in Listmaster Admin menu (#1649)

---

default/sympa.wsdl

This may fix #1676 
This may fix #1696
This supersedes #1677 & #1697

SOAP: Fix typos in sympa.wsdl

---

src/lib/Sympa/Config.pm
src/lib/Sympa/Config/Schema.pm

Missing validation on Digest frequency in Edit Config (#1742)

---

src/lib/Sympa/List.pm

This is a candidate of PR that may fix #1660.

Manually deleted list blocks closure of the list which has been included by the former (#1660)

---

src/cgi/wwsympa.fcgi.in

WWSympa: Save default sort key in review (#1577)

---

default/web_tt2/choosepasswd.tt2
default/web_tt2/config_common.tt2
default/web_tt2/login.tt2
default/web_tt2/pref.tt2

WWSympa: Enable autofilling of password only if necessary

---

default/mail_tt2/invite.tt2

Setting invite sender as From: field should be avoided (#1846)

---

cpanfile
src/lib/Sympa/Tools/Text.pm

WWSympa: Uploaded file names in UTF-8 were garbled (#1802)

---

cpanfile

Update a dependency MIME-EncWords (#1787)

---

default/web_tt2/get_closed_lists.tt2
src/cgi/wwsympa.fcgi.in

This is useful to determine which lists can be purged.

Expose update_epoch on get_closed_lists.

---

default/web_tt2/reviewbouncing.tt2

Incorrect "No bouncing members" on a large list with small number of bouncers (#1842)

---

.github/workflows/make-check.yml
.gitlab-ci.yml
.travis.yml
cpanfile
src/cgi/wwsympa.fcgi.in
src/lib/Sympa/Tools/Text.pm
t/Tools_Text.t

Revert 3a1bbc7 in PR #1885 to postpone making Unicode::UTF8 mandatory.

postpone making Unicode::UTF8 mandatory

---

src/cgi/wwsympa.fcgi.in

See [Sympa SA 2024-001](https://www.sympa.community/security/2024-001.html) (TBD).

[CVE-2024-55919] Improper input validation on generic SSO login

---

src/lib/Sympa/Spindle/TransformIncoming.pm

Bug in custom_subject rendering (#1924)

---

src/lib/Sympa/Aliases/CheckSMTP.pm
src/lib/Sympa/List/Users.pm
src/lib/Sympa/Spool.pm

LISTNAME-request@DOMAIN aliases are not supported (#1922)

---

default/web_tt2/modindex.tt2

Bulk moderation of messages is broken (#1926)
